package com.weshare.thunder.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class DepositProductExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table deposit_product
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table deposit_product
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table deposit_product
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deposit_product
     *
     * @mbggenerated
     */
    public DepositProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deposit_product
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deposit_product
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deposit_product
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deposit_product
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deposit_product
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deposit_product
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deposit_product
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deposit_product
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deposit_product
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deposit_product
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table deposit_product
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Integer value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Integer value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Integer value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Integer value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Integer value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Integer> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Integer> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Integer value1, Integer value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Integer value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Integer value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Integer value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Integer value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Integer value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Integer> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Integer> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Integer value1, Integer value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNull() {
            addCriterion("product_id is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("product_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(Integer value) {
            addCriterion("product_id =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(Integer value) {
            addCriterion("product_id <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(Integer value) {
            addCriterion("product_id >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("product_id >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(Integer value) {
            addCriterion("product_id <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(Integer value) {
            addCriterion("product_id <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<Integer> values) {
            addCriterion("product_id in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<Integer> values) {
            addCriterion("product_id not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(Integer value1, Integer value2) {
            addCriterion("product_id between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(Integer value1, Integer value2) {
            addCriterion("product_id not between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNull() {
            addCriterion("product_name is null");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNotNull() {
            addCriterion("product_name is not null");
            return (Criteria) this;
        }

        public Criteria andProductNameEqualTo(String value) {
            addCriterion("product_name =", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotEqualTo(String value) {
            addCriterion("product_name <>", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThan(String value) {
            addCriterion("product_name >", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThanOrEqualTo(String value) {
            addCriterion("product_name >=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThan(String value) {
            addCriterion("product_name <", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThanOrEqualTo(String value) {
            addCriterion("product_name <=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLike(String value) {
            addCriterion("product_name like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotLike(String value) {
            addCriterion("product_name not like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameIn(List<String> values) {
            addCriterion("product_name in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotIn(List<String> values) {
            addCriterion("product_name not in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameBetween(String value1, String value2) {
            addCriterion("product_name between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotBetween(String value1, String value2) {
            addCriterion("product_name not between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andConditionEntranceIsNull() {
            addCriterion("condition_entrance is null");
            return (Criteria) this;
        }

        public Criteria andConditionEntranceIsNotNull() {
            addCriterion("condition_entrance is not null");
            return (Criteria) this;
        }

        public Criteria andConditionEntranceEqualTo(BigDecimal value) {
            addCriterion("condition_entrance =", value, "conditionEntrance");
            return (Criteria) this;
        }

        public Criteria andConditionEntranceNotEqualTo(BigDecimal value) {
            addCriterion("condition_entrance <>", value, "conditionEntrance");
            return (Criteria) this;
        }

        public Criteria andConditionEntranceGreaterThan(BigDecimal value) {
            addCriterion("condition_entrance >", value, "conditionEntrance");
            return (Criteria) this;
        }

        public Criteria andConditionEntranceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("condition_entrance >=", value, "conditionEntrance");
            return (Criteria) this;
        }

        public Criteria andConditionEntranceLessThan(BigDecimal value) {
            addCriterion("condition_entrance <", value, "conditionEntrance");
            return (Criteria) this;
        }

        public Criteria andConditionEntranceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("condition_entrance <=", value, "conditionEntrance");
            return (Criteria) this;
        }

        public Criteria andConditionEntranceIn(List<BigDecimal> values) {
            addCriterion("condition_entrance in", values, "conditionEntrance");
            return (Criteria) this;
        }

        public Criteria andConditionEntranceNotIn(List<BigDecimal> values) {
            addCriterion("condition_entrance not in", values, "conditionEntrance");
            return (Criteria) this;
        }

        public Criteria andConditionEntranceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("condition_entrance between", value1, value2, "conditionEntrance");
            return (Criteria) this;
        }

        public Criteria andConditionEntranceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("condition_entrance not between", value1, value2, "conditionEntrance");
            return (Criteria) this;
        }

        public Criteria andConditionSingleMinIsNull() {
            addCriterion("condition_single_min is null");
            return (Criteria) this;
        }

        public Criteria andConditionSingleMinIsNotNull() {
            addCriterion("condition_single_min is not null");
            return (Criteria) this;
        }

        public Criteria andConditionSingleMinEqualTo(BigDecimal value) {
            addCriterion("condition_single_min =", value, "conditionSingleMin");
            return (Criteria) this;
        }

        public Criteria andConditionSingleMinNotEqualTo(BigDecimal value) {
            addCriterion("condition_single_min <>", value, "conditionSingleMin");
            return (Criteria) this;
        }

        public Criteria andConditionSingleMinGreaterThan(BigDecimal value) {
            addCriterion("condition_single_min >", value, "conditionSingleMin");
            return (Criteria) this;
        }

        public Criteria andConditionSingleMinGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("condition_single_min >=", value, "conditionSingleMin");
            return (Criteria) this;
        }

        public Criteria andConditionSingleMinLessThan(BigDecimal value) {
            addCriterion("condition_single_min <", value, "conditionSingleMin");
            return (Criteria) this;
        }

        public Criteria andConditionSingleMinLessThanOrEqualTo(BigDecimal value) {
            addCriterion("condition_single_min <=", value, "conditionSingleMin");
            return (Criteria) this;
        }

        public Criteria andConditionSingleMinIn(List<BigDecimal> values) {
            addCriterion("condition_single_min in", values, "conditionSingleMin");
            return (Criteria) this;
        }

        public Criteria andConditionSingleMinNotIn(List<BigDecimal> values) {
            addCriterion("condition_single_min not in", values, "conditionSingleMin");
            return (Criteria) this;
        }

        public Criteria andConditionSingleMinBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("condition_single_min between", value1, value2, "conditionSingleMin");
            return (Criteria) this;
        }

        public Criteria andConditionSingleMinNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("condition_single_min not between", value1, value2, "conditionSingleMin");
            return (Criteria) this;
        }

        public Criteria andConditionPersonMaxIsNull() {
            addCriterion("condition_person_max is null");
            return (Criteria) this;
        }

        public Criteria andConditionPersonMaxIsNotNull() {
            addCriterion("condition_person_max is not null");
            return (Criteria) this;
        }

        public Criteria andConditionPersonMaxEqualTo(BigDecimal value) {
            addCriterion("condition_person_max =", value, "conditionPersonMax");
            return (Criteria) this;
        }

        public Criteria andConditionPersonMaxNotEqualTo(BigDecimal value) {
            addCriterion("condition_person_max <>", value, "conditionPersonMax");
            return (Criteria) this;
        }

        public Criteria andConditionPersonMaxGreaterThan(BigDecimal value) {
            addCriterion("condition_person_max >", value, "conditionPersonMax");
            return (Criteria) this;
        }

        public Criteria andConditionPersonMaxGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("condition_person_max >=", value, "conditionPersonMax");
            return (Criteria) this;
        }

        public Criteria andConditionPersonMaxLessThan(BigDecimal value) {
            addCriterion("condition_person_max <", value, "conditionPersonMax");
            return (Criteria) this;
        }

        public Criteria andConditionPersonMaxLessThanOrEqualTo(BigDecimal value) {
            addCriterion("condition_person_max <=", value, "conditionPersonMax");
            return (Criteria) this;
        }

        public Criteria andConditionPersonMaxIn(List<BigDecimal> values) {
            addCriterion("condition_person_max in", values, "conditionPersonMax");
            return (Criteria) this;
        }

        public Criteria andConditionPersonMaxNotIn(List<BigDecimal> values) {
            addCriterion("condition_person_max not in", values, "conditionPersonMax");
            return (Criteria) this;
        }

        public Criteria andConditionPersonMaxBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("condition_person_max between", value1, value2, "conditionPersonMax");
            return (Criteria) this;
        }

        public Criteria andConditionPersonMaxNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("condition_person_max not between", value1, value2, "conditionPersonMax");
            return (Criteria) this;
        }

        public Criteria andConditionMaxIsNull() {
            addCriterion("condition_max is null");
            return (Criteria) this;
        }

        public Criteria andConditionMaxIsNotNull() {
            addCriterion("condition_max is not null");
            return (Criteria) this;
        }

        public Criteria andConditionMaxEqualTo(BigDecimal value) {
            addCriterion("condition_max =", value, "conditionMax");
            return (Criteria) this;
        }

        public Criteria andConditionMaxNotEqualTo(BigDecimal value) {
            addCriterion("condition_max <>", value, "conditionMax");
            return (Criteria) this;
        }

        public Criteria andConditionMaxGreaterThan(BigDecimal value) {
            addCriterion("condition_max >", value, "conditionMax");
            return (Criteria) this;
        }

        public Criteria andConditionMaxGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("condition_max >=", value, "conditionMax");
            return (Criteria) this;
        }

        public Criteria andConditionMaxLessThan(BigDecimal value) {
            addCriterion("condition_max <", value, "conditionMax");
            return (Criteria) this;
        }

        public Criteria andConditionMaxLessThanOrEqualTo(BigDecimal value) {
            addCriterion("condition_max <=", value, "conditionMax");
            return (Criteria) this;
        }

        public Criteria andConditionMaxIn(List<BigDecimal> values) {
            addCriterion("condition_max in", values, "conditionMax");
            return (Criteria) this;
        }

        public Criteria andConditionMaxNotIn(List<BigDecimal> values) {
            addCriterion("condition_max not in", values, "conditionMax");
            return (Criteria) this;
        }

        public Criteria andConditionMaxBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("condition_max between", value1, value2, "conditionMax");
            return (Criteria) this;
        }

        public Criteria andConditionMaxNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("condition_max not between", value1, value2, "conditionMax");
            return (Criteria) this;
        }

        public Criteria andPeriodIsNull() {
            addCriterion("period is null");
            return (Criteria) this;
        }

        public Criteria andPeriodIsNotNull() {
            addCriterion("period is not null");
            return (Criteria) this;
        }

        public Criteria andPeriodEqualTo(Integer value) {
            addCriterion("period =", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodNotEqualTo(Integer value) {
            addCriterion("period <>", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodGreaterThan(Integer value) {
            addCriterion("period >", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodGreaterThanOrEqualTo(Integer value) {
            addCriterion("period >=", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodLessThan(Integer value) {
            addCriterion("period <", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodLessThanOrEqualTo(Integer value) {
            addCriterion("period <=", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodIn(List<Integer> values) {
            addCriterion("period in", values, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodNotIn(List<Integer> values) {
            addCriterion("period not in", values, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodBetween(Integer value1, Integer value2) {
            addCriterion("period between", value1, value2, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodNotBetween(Integer value1, Integer value2) {
            addCriterion("period not between", value1, value2, "period");
            return (Criteria) this;
        }

        public Criteria andBaseRateIsNull() {
            addCriterion("base_rate is null");
            return (Criteria) this;
        }

        public Criteria andBaseRateIsNotNull() {
            addCriterion("base_rate is not null");
            return (Criteria) this;
        }

        public Criteria andBaseRateEqualTo(BigDecimal value) {
            addCriterion("base_rate =", value, "baseRate");
            return (Criteria) this;
        }

        public Criteria andBaseRateNotEqualTo(BigDecimal value) {
            addCriterion("base_rate <>", value, "baseRate");
            return (Criteria) this;
        }

        public Criteria andBaseRateGreaterThan(BigDecimal value) {
            addCriterion("base_rate >", value, "baseRate");
            return (Criteria) this;
        }

        public Criteria andBaseRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("base_rate >=", value, "baseRate");
            return (Criteria) this;
        }

        public Criteria andBaseRateLessThan(BigDecimal value) {
            addCriterion("base_rate <", value, "baseRate");
            return (Criteria) this;
        }

        public Criteria andBaseRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("base_rate <=", value, "baseRate");
            return (Criteria) this;
        }

        public Criteria andBaseRateIn(List<BigDecimal> values) {
            addCriterion("base_rate in", values, "baseRate");
            return (Criteria) this;
        }

        public Criteria andBaseRateNotIn(List<BigDecimal> values) {
            addCriterion("base_rate not in", values, "baseRate");
            return (Criteria) this;
        }

        public Criteria andBaseRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("base_rate between", value1, value2, "baseRate");
            return (Criteria) this;
        }

        public Criteria andBaseRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("base_rate not between", value1, value2, "baseRate");
            return (Criteria) this;
        }

        public Criteria andCanWithdrawAnytimeIsNull() {
            addCriterion("can_withdraw_anytime is null");
            return (Criteria) this;
        }

        public Criteria andCanWithdrawAnytimeIsNotNull() {
            addCriterion("can_withdraw_anytime is not null");
            return (Criteria) this;
        }

        public Criteria andCanWithdrawAnytimeEqualTo(Boolean value) {
            addCriterion("can_withdraw_anytime =", value, "canWithdrawAnytime");
            return (Criteria) this;
        }

        public Criteria andCanWithdrawAnytimeNotEqualTo(Boolean value) {
            addCriterion("can_withdraw_anytime <>", value, "canWithdrawAnytime");
            return (Criteria) this;
        }

        public Criteria andCanWithdrawAnytimeGreaterThan(Boolean value) {
            addCriterion("can_withdraw_anytime >", value, "canWithdrawAnytime");
            return (Criteria) this;
        }

        public Criteria andCanWithdrawAnytimeGreaterThanOrEqualTo(Boolean value) {
            addCriterion("can_withdraw_anytime >=", value, "canWithdrawAnytime");
            return (Criteria) this;
        }

        public Criteria andCanWithdrawAnytimeLessThan(Boolean value) {
            addCriterion("can_withdraw_anytime <", value, "canWithdrawAnytime");
            return (Criteria) this;
        }

        public Criteria andCanWithdrawAnytimeLessThanOrEqualTo(Boolean value) {
            addCriterion("can_withdraw_anytime <=", value, "canWithdrawAnytime");
            return (Criteria) this;
        }

        public Criteria andCanWithdrawAnytimeIn(List<Boolean> values) {
            addCriterion("can_withdraw_anytime in", values, "canWithdrawAnytime");
            return (Criteria) this;
        }

        public Criteria andCanWithdrawAnytimeNotIn(List<Boolean> values) {
            addCriterion("can_withdraw_anytime not in", values, "canWithdrawAnytime");
            return (Criteria) this;
        }

        public Criteria andCanWithdrawAnytimeBetween(Boolean value1, Boolean value2) {
            addCriterion("can_withdraw_anytime between", value1, value2, "canWithdrawAnytime");
            return (Criteria) this;
        }

        public Criteria andCanWithdrawAnytimeNotBetween(Boolean value1, Boolean value2) {
            addCriterion("can_withdraw_anytime not between", value1, value2, "canWithdrawAnytime");
            return (Criteria) this;
        }

        public Criteria andAnytimeFeeRateIsNull() {
            addCriterion("anytime_fee_rate is null");
            return (Criteria) this;
        }

        public Criteria andAnytimeFeeRateIsNotNull() {
            addCriterion("anytime_fee_rate is not null");
            return (Criteria) this;
        }

        public Criteria andAnytimeFeeRateEqualTo(BigDecimal value) {
            addCriterion("anytime_fee_rate =", value, "anytimeFeeRate");
            return (Criteria) this;
        }

        public Criteria andAnytimeFeeRateNotEqualTo(BigDecimal value) {
            addCriterion("anytime_fee_rate <>", value, "anytimeFeeRate");
            return (Criteria) this;
        }

        public Criteria andAnytimeFeeRateGreaterThan(BigDecimal value) {
            addCriterion("anytime_fee_rate >", value, "anytimeFeeRate");
            return (Criteria) this;
        }

        public Criteria andAnytimeFeeRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("anytime_fee_rate >=", value, "anytimeFeeRate");
            return (Criteria) this;
        }

        public Criteria andAnytimeFeeRateLessThan(BigDecimal value) {
            addCriterion("anytime_fee_rate <", value, "anytimeFeeRate");
            return (Criteria) this;
        }

        public Criteria andAnytimeFeeRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("anytime_fee_rate <=", value, "anytimeFeeRate");
            return (Criteria) this;
        }

        public Criteria andAnytimeFeeRateIn(List<BigDecimal> values) {
            addCriterion("anytime_fee_rate in", values, "anytimeFeeRate");
            return (Criteria) this;
        }

        public Criteria andAnytimeFeeRateNotIn(List<BigDecimal> values) {
            addCriterion("anytime_fee_rate not in", values, "anytimeFeeRate");
            return (Criteria) this;
        }

        public Criteria andAnytimeFeeRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("anytime_fee_rate between", value1, value2, "anytimeFeeRate");
            return (Criteria) this;
        }

        public Criteria andAnytimeFeeRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("anytime_fee_rate not between", value1, value2, "anytimeFeeRate");
            return (Criteria) this;
        }

        public Criteria andProductGroupIdIsNull() {
            addCriterion("product_group_id is null");
            return (Criteria) this;
        }

        public Criteria andProductGroupIdIsNotNull() {
            addCriterion("product_group_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductGroupIdEqualTo(Integer value) {
            addCriterion("product_group_id =", value, "productGroupId");
            return (Criteria) this;
        }

        public Criteria andProductGroupIdNotEqualTo(Integer value) {
            addCriterion("product_group_id <>", value, "productGroupId");
            return (Criteria) this;
        }

        public Criteria andProductGroupIdGreaterThan(Integer value) {
            addCriterion("product_group_id >", value, "productGroupId");
            return (Criteria) this;
        }

        public Criteria andProductGroupIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("product_group_id >=", value, "productGroupId");
            return (Criteria) this;
        }

        public Criteria andProductGroupIdLessThan(Integer value) {
            addCriterion("product_group_id <", value, "productGroupId");
            return (Criteria) this;
        }

        public Criteria andProductGroupIdLessThanOrEqualTo(Integer value) {
            addCriterion("product_group_id <=", value, "productGroupId");
            return (Criteria) this;
        }

        public Criteria andProductGroupIdIn(List<Integer> values) {
            addCriterion("product_group_id in", values, "productGroupId");
            return (Criteria) this;
        }

        public Criteria andProductGroupIdNotIn(List<Integer> values) {
            addCriterion("product_group_id not in", values, "productGroupId");
            return (Criteria) this;
        }

        public Criteria andProductGroupIdBetween(Integer value1, Integer value2) {
            addCriterion("product_group_id between", value1, value2, "productGroupId");
            return (Criteria) this;
        }

        public Criteria andProductGroupIdNotBetween(Integer value1, Integer value2) {
            addCriterion("product_group_id not between", value1, value2, "productGroupId");
            return (Criteria) this;
        }

        public Criteria andRemark1IsNull() {
            addCriterion("remark1 is null");
            return (Criteria) this;
        }

        public Criteria andRemark1IsNotNull() {
            addCriterion("remark1 is not null");
            return (Criteria) this;
        }

        public Criteria andRemark1EqualTo(String value) {
            addCriterion("remark1 =", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1NotEqualTo(String value) {
            addCriterion("remark1 <>", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1GreaterThan(String value) {
            addCriterion("remark1 >", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1GreaterThanOrEqualTo(String value) {
            addCriterion("remark1 >=", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1LessThan(String value) {
            addCriterion("remark1 <", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1LessThanOrEqualTo(String value) {
            addCriterion("remark1 <=", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1Like(String value) {
            addCriterion("remark1 like", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1NotLike(String value) {
            addCriterion("remark1 not like", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1In(List<String> values) {
            addCriterion("remark1 in", values, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1NotIn(List<String> values) {
            addCriterion("remark1 not in", values, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1Between(String value1, String value2) {
            addCriterion("remark1 between", value1, value2, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1NotBetween(String value1, String value2) {
            addCriterion("remark1 not between", value1, value2, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark2IsNull() {
            addCriterion("remark2 is null");
            return (Criteria) this;
        }

        public Criteria andRemark2IsNotNull() {
            addCriterion("remark2 is not null");
            return (Criteria) this;
        }

        public Criteria andRemark2EqualTo(String value) {
            addCriterion("remark2 =", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2NotEqualTo(String value) {
            addCriterion("remark2 <>", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2GreaterThan(String value) {
            addCriterion("remark2 >", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2GreaterThanOrEqualTo(String value) {
            addCriterion("remark2 >=", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2LessThan(String value) {
            addCriterion("remark2 <", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2LessThanOrEqualTo(String value) {
            addCriterion("remark2 <=", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2Like(String value) {
            addCriterion("remark2 like", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2NotLike(String value) {
            addCriterion("remark2 not like", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2In(List<String> values) {
            addCriterion("remark2 in", values, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2NotIn(List<String> values) {
            addCriterion("remark2 not in", values, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2Between(String value1, String value2) {
            addCriterion("remark2 between", value1, value2, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2NotBetween(String value1, String value2) {
            addCriterion("remark2 not between", value1, value2, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark3IsNull() {
            addCriterion("remark3 is null");
            return (Criteria) this;
        }

        public Criteria andRemark3IsNotNull() {
            addCriterion("remark3 is not null");
            return (Criteria) this;
        }

        public Criteria andRemark3EqualTo(String value) {
            addCriterion("remark3 =", value, "remark3");
            return (Criteria) this;
        }

        public Criteria andRemark3NotEqualTo(String value) {
            addCriterion("remark3 <>", value, "remark3");
            return (Criteria) this;
        }

        public Criteria andRemark3GreaterThan(String value) {
            addCriterion("remark3 >", value, "remark3");
            return (Criteria) this;
        }

        public Criteria andRemark3GreaterThanOrEqualTo(String value) {
            addCriterion("remark3 >=", value, "remark3");
            return (Criteria) this;
        }

        public Criteria andRemark3LessThan(String value) {
            addCriterion("remark3 <", value, "remark3");
            return (Criteria) this;
        }

        public Criteria andRemark3LessThanOrEqualTo(String value) {
            addCriterion("remark3 <=", value, "remark3");
            return (Criteria) this;
        }

        public Criteria andRemark3Like(String value) {
            addCriterion("remark3 like", value, "remark3");
            return (Criteria) this;
        }

        public Criteria andRemark3NotLike(String value) {
            addCriterion("remark3 not like", value, "remark3");
            return (Criteria) this;
        }

        public Criteria andRemark3In(List<String> values) {
            addCriterion("remark3 in", values, "remark3");
            return (Criteria) this;
        }

        public Criteria andRemark3NotIn(List<String> values) {
            addCriterion("remark3 not in", values, "remark3");
            return (Criteria) this;
        }

        public Criteria andRemark3Between(String value1, String value2) {
            addCriterion("remark3 between", value1, value2, "remark3");
            return (Criteria) this;
        }

        public Criteria andRemark3NotBetween(String value1, String value2) {
            addCriterion("remark3 not between", value1, value2, "remark3");
            return (Criteria) this;
        }

        public Criteria andShortDescIsNull() {
            addCriterion("short_desc is null");
            return (Criteria) this;
        }

        public Criteria andShortDescIsNotNull() {
            addCriterion("short_desc is not null");
            return (Criteria) this;
        }

        public Criteria andShortDescEqualTo(String value) {
            addCriterion("short_desc =", value, "shortDesc");
            return (Criteria) this;
        }

        public Criteria andShortDescNotEqualTo(String value) {
            addCriterion("short_desc <>", value, "shortDesc");
            return (Criteria) this;
        }

        public Criteria andShortDescGreaterThan(String value) {
            addCriterion("short_desc >", value, "shortDesc");
            return (Criteria) this;
        }

        public Criteria andShortDescGreaterThanOrEqualTo(String value) {
            addCriterion("short_desc >=", value, "shortDesc");
            return (Criteria) this;
        }

        public Criteria andShortDescLessThan(String value) {
            addCriterion("short_desc <", value, "shortDesc");
            return (Criteria) this;
        }

        public Criteria andShortDescLessThanOrEqualTo(String value) {
            addCriterion("short_desc <=", value, "shortDesc");
            return (Criteria) this;
        }

        public Criteria andShortDescLike(String value) {
            addCriterion("short_desc like", value, "shortDesc");
            return (Criteria) this;
        }

        public Criteria andShortDescNotLike(String value) {
            addCriterion("short_desc not like", value, "shortDesc");
            return (Criteria) this;
        }

        public Criteria andShortDescIn(List<String> values) {
            addCriterion("short_desc in", values, "shortDesc");
            return (Criteria) this;
        }

        public Criteria andShortDescNotIn(List<String> values) {
            addCriterion("short_desc not in", values, "shortDesc");
            return (Criteria) this;
        }

        public Criteria andShortDescBetween(String value1, String value2) {
            addCriterion("short_desc between", value1, value2, "shortDesc");
            return (Criteria) this;
        }

        public Criteria andShortDescNotBetween(String value1, String value2) {
            addCriterion("short_desc not between", value1, value2, "shortDesc");
            return (Criteria) this;
        }

        public Criteria andTimeWindowStartIsNull() {
            addCriterion("time_window_start is null");
            return (Criteria) this;
        }

        public Criteria andTimeWindowStartIsNotNull() {
            addCriterion("time_window_start is not null");
            return (Criteria) this;
        }

        public Criteria andTimeWindowStartEqualTo(Integer value) {
            addCriterion("time_window_start =", value, "timeWindowStart");
            return (Criteria) this;
        }

        public Criteria andTimeWindowStartNotEqualTo(Integer value) {
            addCriterion("time_window_start <>", value, "timeWindowStart");
            return (Criteria) this;
        }

        public Criteria andTimeWindowStartGreaterThan(Integer value) {
            addCriterion("time_window_start >", value, "timeWindowStart");
            return (Criteria) this;
        }

        public Criteria andTimeWindowStartGreaterThanOrEqualTo(Integer value) {
            addCriterion("time_window_start >=", value, "timeWindowStart");
            return (Criteria) this;
        }

        public Criteria andTimeWindowStartLessThan(Integer value) {
            addCriterion("time_window_start <", value, "timeWindowStart");
            return (Criteria) this;
        }

        public Criteria andTimeWindowStartLessThanOrEqualTo(Integer value) {
            addCriterion("time_window_start <=", value, "timeWindowStart");
            return (Criteria) this;
        }

        public Criteria andTimeWindowStartIn(List<Integer> values) {
            addCriterion("time_window_start in", values, "timeWindowStart");
            return (Criteria) this;
        }

        public Criteria andTimeWindowStartNotIn(List<Integer> values) {
            addCriterion("time_window_start not in", values, "timeWindowStart");
            return (Criteria) this;
        }

        public Criteria andTimeWindowStartBetween(Integer value1, Integer value2) {
            addCriterion("time_window_start between", value1, value2, "timeWindowStart");
            return (Criteria) this;
        }

        public Criteria andTimeWindowStartNotBetween(Integer value1, Integer value2) {
            addCriterion("time_window_start not between", value1, value2, "timeWindowStart");
            return (Criteria) this;
        }

        public Criteria andTimeWindowEndIsNull() {
            addCriterion("time_window_end is null");
            return (Criteria) this;
        }

        public Criteria andTimeWindowEndIsNotNull() {
            addCriterion("time_window_end is not null");
            return (Criteria) this;
        }

        public Criteria andTimeWindowEndEqualTo(Integer value) {
            addCriterion("time_window_end =", value, "timeWindowEnd");
            return (Criteria) this;
        }

        public Criteria andTimeWindowEndNotEqualTo(Integer value) {
            addCriterion("time_window_end <>", value, "timeWindowEnd");
            return (Criteria) this;
        }

        public Criteria andTimeWindowEndGreaterThan(Integer value) {
            addCriterion("time_window_end >", value, "timeWindowEnd");
            return (Criteria) this;
        }

        public Criteria andTimeWindowEndGreaterThanOrEqualTo(Integer value) {
            addCriterion("time_window_end >=", value, "timeWindowEnd");
            return (Criteria) this;
        }

        public Criteria andTimeWindowEndLessThan(Integer value) {
            addCriterion("time_window_end <", value, "timeWindowEnd");
            return (Criteria) this;
        }

        public Criteria andTimeWindowEndLessThanOrEqualTo(Integer value) {
            addCriterion("time_window_end <=", value, "timeWindowEnd");
            return (Criteria) this;
        }

        public Criteria andTimeWindowEndIn(List<Integer> values) {
            addCriterion("time_window_end in", values, "timeWindowEnd");
            return (Criteria) this;
        }

        public Criteria andTimeWindowEndNotIn(List<Integer> values) {
            addCriterion("time_window_end not in", values, "timeWindowEnd");
            return (Criteria) this;
        }

        public Criteria andTimeWindowEndBetween(Integer value1, Integer value2) {
            addCriterion("time_window_end between", value1, value2, "timeWindowEnd");
            return (Criteria) this;
        }

        public Criteria andTimeWindowEndNotBetween(Integer value1, Integer value2) {
            addCriterion("time_window_end not between", value1, value2, "timeWindowEnd");
            return (Criteria) this;
        }

        public Criteria andSupportVoucherIsNull() {
            addCriterion("support_voucher is null");
            return (Criteria) this;
        }

        public Criteria andSupportVoucherIsNotNull() {
            addCriterion("support_voucher is not null");
            return (Criteria) this;
        }

        public Criteria andSupportVoucherEqualTo(Boolean value) {
            addCriterion("support_voucher =", value, "supportVoucher");
            return (Criteria) this;
        }

        public Criteria andSupportVoucherNotEqualTo(Boolean value) {
            addCriterion("support_voucher <>", value, "supportVoucher");
            return (Criteria) this;
        }

        public Criteria andSupportVoucherGreaterThan(Boolean value) {
            addCriterion("support_voucher >", value, "supportVoucher");
            return (Criteria) this;
        }

        public Criteria andSupportVoucherGreaterThanOrEqualTo(Boolean value) {
            addCriterion("support_voucher >=", value, "supportVoucher");
            return (Criteria) this;
        }

        public Criteria andSupportVoucherLessThan(Boolean value) {
            addCriterion("support_voucher <", value, "supportVoucher");
            return (Criteria) this;
        }

        public Criteria andSupportVoucherLessThanOrEqualTo(Boolean value) {
            addCriterion("support_voucher <=", value, "supportVoucher");
            return (Criteria) this;
        }

        public Criteria andSupportVoucherIn(List<Boolean> values) {
            addCriterion("support_voucher in", values, "supportVoucher");
            return (Criteria) this;
        }

        public Criteria andSupportVoucherNotIn(List<Boolean> values) {
            addCriterion("support_voucher not in", values, "supportVoucher");
            return (Criteria) this;
        }

        public Criteria andSupportVoucherBetween(Boolean value1, Boolean value2) {
            addCriterion("support_voucher between", value1, value2, "supportVoucher");
            return (Criteria) this;
        }

        public Criteria andSupportVoucherNotBetween(Boolean value1, Boolean value2) {
            addCriterion("support_voucher not between", value1, value2, "supportVoucher");
            return (Criteria) this;
        }

        public Criteria andIsValidIsNull() {
            addCriterion("is_valid is null");
            return (Criteria) this;
        }

        public Criteria andIsValidIsNotNull() {
            addCriterion("is_valid is not null");
            return (Criteria) this;
        }

        public Criteria andIsValidEqualTo(Boolean value) {
            addCriterion("is_valid =", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotEqualTo(Boolean value) {
            addCriterion("is_valid <>", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidGreaterThan(Boolean value) {
            addCriterion("is_valid >", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_valid >=", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidLessThan(Boolean value) {
            addCriterion("is_valid <", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidLessThanOrEqualTo(Boolean value) {
            addCriterion("is_valid <=", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidIn(List<Boolean> values) {
            addCriterion("is_valid in", values, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotIn(List<Boolean> values) {
            addCriterion("is_valid not in", values, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidBetween(Boolean value1, Boolean value2) {
            addCriterion("is_valid between", value1, value2, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_valid not between", value1, value2, "isValid");
            return (Criteria) this;
        }

        public Criteria andCornerMarkPropIsNull() {
            addCriterion("corner_mark_prop is null");
            return (Criteria) this;
        }

        public Criteria andCornerMarkPropIsNotNull() {
            addCriterion("corner_mark_prop is not null");
            return (Criteria) this;
        }

        public Criteria andCornerMarkPropEqualTo(Byte value) {
            addCriterion("corner_mark_prop =", value, "cornerMarkProp");
            return (Criteria) this;
        }

        public Criteria andCornerMarkPropNotEqualTo(Byte value) {
            addCriterion("corner_mark_prop <>", value, "cornerMarkProp");
            return (Criteria) this;
        }

        public Criteria andCornerMarkPropGreaterThan(Byte value) {
            addCriterion("corner_mark_prop >", value, "cornerMarkProp");
            return (Criteria) this;
        }

        public Criteria andCornerMarkPropGreaterThanOrEqualTo(Byte value) {
            addCriterion("corner_mark_prop >=", value, "cornerMarkProp");
            return (Criteria) this;
        }

        public Criteria andCornerMarkPropLessThan(Byte value) {
            addCriterion("corner_mark_prop <", value, "cornerMarkProp");
            return (Criteria) this;
        }

        public Criteria andCornerMarkPropLessThanOrEqualTo(Byte value) {
            addCriterion("corner_mark_prop <=", value, "cornerMarkProp");
            return (Criteria) this;
        }

        public Criteria andCornerMarkPropIn(List<Byte> values) {
            addCriterion("corner_mark_prop in", values, "cornerMarkProp");
            return (Criteria) this;
        }

        public Criteria andCornerMarkPropNotIn(List<Byte> values) {
            addCriterion("corner_mark_prop not in", values, "cornerMarkProp");
            return (Criteria) this;
        }

        public Criteria andCornerMarkPropBetween(Byte value1, Byte value2) {
            addCriterion("corner_mark_prop between", value1, value2, "cornerMarkProp");
            return (Criteria) this;
        }

        public Criteria andCornerMarkPropNotBetween(Byte value1, Byte value2) {
            addCriterion("corner_mark_prop not between", value1, value2, "cornerMarkProp");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table deposit_product
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table deposit_product
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}