package com.weshare.thunder.model;

import java.math.BigDecimal;

public class DepositProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deposit_product.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deposit_product.create_time
     *
     * @mbggenerated
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deposit_product.update_time
     *
     * @mbggenerated
     */
    private Integer updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deposit_product.product_id
     *
     * @mbggenerated
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deposit_product.product_name
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deposit_product.condition_entrance
     *
     * @mbggenerated
     */
    private BigDecimal conditionEntrance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deposit_product.condition_single_min
     *
     * @mbggenerated
     */
    private BigDecimal conditionSingleMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deposit_product.condition_person_max
     *
     * @mbggenerated
     */
    private BigDecimal conditionPersonMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deposit_product.condition_max
     *
     * @mbggenerated
     */
    private BigDecimal conditionMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deposit_product.period
     *
     * @mbggenerated
     */
    private Integer period;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deposit_product.base_rate
     *
     * @mbggenerated
     */
    private BigDecimal baseRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deposit_product.can_withdraw_anytime
     *
     * @mbggenerated
     */
    private Boolean canWithdrawAnytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deposit_product.anytime_fee_rate
     *
     * @mbggenerated
     */
    private BigDecimal anytimeFeeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deposit_product.product_group_id
     *
     * @mbggenerated
     */
    private Integer productGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deposit_product.remark1
     *
     * @mbggenerated
     */
    private String remark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deposit_product.remark2
     *
     * @mbggenerated
     */
    private String remark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deposit_product.remark3
     *
     * @mbggenerated
     */
    private String remark3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deposit_product.short_desc
     *
     * @mbggenerated
     */
    private String shortDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deposit_product.time_window_start
     *
     * @mbggenerated
     */
    private Integer timeWindowStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deposit_product.time_window_end
     *
     * @mbggenerated
     */
    private Integer timeWindowEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deposit_product.support_voucher
     *
     * @mbggenerated
     */
    private Boolean supportVoucher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deposit_product.is_valid
     *
     * @mbggenerated
     */
    private Boolean isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deposit_product.corner_mark_prop
     *
     * @mbggenerated
     */
    private Byte cornerMarkProp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deposit_product.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deposit_product.id
     *
     * @return the value of deposit_product.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deposit_product.id
     *
     * @param id the value for deposit_product.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deposit_product.create_time
     *
     * @return the value of deposit_product.create_time
     *
     * @mbggenerated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deposit_product.create_time
     *
     * @param createTime the value for deposit_product.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deposit_product.update_time
     *
     * @return the value of deposit_product.update_time
     *
     * @mbggenerated
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deposit_product.update_time
     *
     * @param updateTime the value for deposit_product.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deposit_product.product_id
     *
     * @return the value of deposit_product.product_id
     *
     * @mbggenerated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deposit_product.product_id
     *
     * @param productId the value for deposit_product.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deposit_product.product_name
     *
     * @return the value of deposit_product.product_name
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deposit_product.product_name
     *
     * @param productName the value for deposit_product.product_name
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deposit_product.condition_entrance
     *
     * @return the value of deposit_product.condition_entrance
     *
     * @mbggenerated
     */
    public BigDecimal getConditionEntrance() {
        return conditionEntrance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deposit_product.condition_entrance
     *
     * @param conditionEntrance the value for deposit_product.condition_entrance
     *
     * @mbggenerated
     */
    public void setConditionEntrance(BigDecimal conditionEntrance) {
        this.conditionEntrance = conditionEntrance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deposit_product.condition_single_min
     *
     * @return the value of deposit_product.condition_single_min
     *
     * @mbggenerated
     */
    public BigDecimal getConditionSingleMin() {
        return conditionSingleMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deposit_product.condition_single_min
     *
     * @param conditionSingleMin the value for deposit_product.condition_single_min
     *
     * @mbggenerated
     */
    public void setConditionSingleMin(BigDecimal conditionSingleMin) {
        this.conditionSingleMin = conditionSingleMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deposit_product.condition_person_max
     *
     * @return the value of deposit_product.condition_person_max
     *
     * @mbggenerated
     */
    public BigDecimal getConditionPersonMax() {
        return conditionPersonMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deposit_product.condition_person_max
     *
     * @param conditionPersonMax the value for deposit_product.condition_person_max
     *
     * @mbggenerated
     */
    public void setConditionPersonMax(BigDecimal conditionPersonMax) {
        this.conditionPersonMax = conditionPersonMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deposit_product.condition_max
     *
     * @return the value of deposit_product.condition_max
     *
     * @mbggenerated
     */
    public BigDecimal getConditionMax() {
        return conditionMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deposit_product.condition_max
     *
     * @param conditionMax the value for deposit_product.condition_max
     *
     * @mbggenerated
     */
    public void setConditionMax(BigDecimal conditionMax) {
        this.conditionMax = conditionMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deposit_product.period
     *
     * @return the value of deposit_product.period
     *
     * @mbggenerated
     */
    public Integer getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deposit_product.period
     *
     * @param period the value for deposit_product.period
     *
     * @mbggenerated
     */
    public void setPeriod(Integer period) {
        this.period = period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deposit_product.base_rate
     *
     * @return the value of deposit_product.base_rate
     *
     * @mbggenerated
     */
    public BigDecimal getBaseRate() {
        return baseRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deposit_product.base_rate
     *
     * @param baseRate the value for deposit_product.base_rate
     *
     * @mbggenerated
     */
    public void setBaseRate(BigDecimal baseRate) {
        this.baseRate = baseRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deposit_product.can_withdraw_anytime
     *
     * @return the value of deposit_product.can_withdraw_anytime
     *
     * @mbggenerated
     */
    public Boolean getCanWithdrawAnytime() {
        return canWithdrawAnytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deposit_product.can_withdraw_anytime
     *
     * @param canWithdrawAnytime the value for deposit_product.can_withdraw_anytime
     *
     * @mbggenerated
     */
    public void setCanWithdrawAnytime(Boolean canWithdrawAnytime) {
        this.canWithdrawAnytime = canWithdrawAnytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deposit_product.anytime_fee_rate
     *
     * @return the value of deposit_product.anytime_fee_rate
     *
     * @mbggenerated
     */
    public BigDecimal getAnytimeFeeRate() {
        return anytimeFeeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deposit_product.anytime_fee_rate
     *
     * @param anytimeFeeRate the value for deposit_product.anytime_fee_rate
     *
     * @mbggenerated
     */
    public void setAnytimeFeeRate(BigDecimal anytimeFeeRate) {
        this.anytimeFeeRate = anytimeFeeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deposit_product.product_group_id
     *
     * @return the value of deposit_product.product_group_id
     *
     * @mbggenerated
     */
    public Integer getProductGroupId() {
        return productGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deposit_product.product_group_id
     *
     * @param productGroupId the value for deposit_product.product_group_id
     *
     * @mbggenerated
     */
    public void setProductGroupId(Integer productGroupId) {
        this.productGroupId = productGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deposit_product.remark1
     *
     * @return the value of deposit_product.remark1
     *
     * @mbggenerated
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deposit_product.remark1
     *
     * @param remark1 the value for deposit_product.remark1
     *
     * @mbggenerated
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deposit_product.remark2
     *
     * @return the value of deposit_product.remark2
     *
     * @mbggenerated
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deposit_product.remark2
     *
     * @param remark2 the value for deposit_product.remark2
     *
     * @mbggenerated
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deposit_product.remark3
     *
     * @return the value of deposit_product.remark3
     *
     * @mbggenerated
     */
    public String getRemark3() {
        return remark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deposit_product.remark3
     *
     * @param remark3 the value for deposit_product.remark3
     *
     * @mbggenerated
     */
    public void setRemark3(String remark3) {
        this.remark3 = remark3 == null ? null : remark3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deposit_product.short_desc
     *
     * @return the value of deposit_product.short_desc
     *
     * @mbggenerated
     */
    public String getShortDesc() {
        return shortDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deposit_product.short_desc
     *
     * @param shortDesc the value for deposit_product.short_desc
     *
     * @mbggenerated
     */
    public void setShortDesc(String shortDesc) {
        this.shortDesc = shortDesc == null ? null : shortDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deposit_product.time_window_start
     *
     * @return the value of deposit_product.time_window_start
     *
     * @mbggenerated
     */
    public Integer getTimeWindowStart() {
        return timeWindowStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deposit_product.time_window_start
     *
     * @param timeWindowStart the value for deposit_product.time_window_start
     *
     * @mbggenerated
     */
    public void setTimeWindowStart(Integer timeWindowStart) {
        this.timeWindowStart = timeWindowStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deposit_product.time_window_end
     *
     * @return the value of deposit_product.time_window_end
     *
     * @mbggenerated
     */
    public Integer getTimeWindowEnd() {
        return timeWindowEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deposit_product.time_window_end
     *
     * @param timeWindowEnd the value for deposit_product.time_window_end
     *
     * @mbggenerated
     */
    public void setTimeWindowEnd(Integer timeWindowEnd) {
        this.timeWindowEnd = timeWindowEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deposit_product.support_voucher
     *
     * @return the value of deposit_product.support_voucher
     *
     * @mbggenerated
     */
    public Boolean getSupportVoucher() {
        return supportVoucher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deposit_product.support_voucher
     *
     * @param supportVoucher the value for deposit_product.support_voucher
     *
     * @mbggenerated
     */
    public void setSupportVoucher(Boolean supportVoucher) {
        this.supportVoucher = supportVoucher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deposit_product.is_valid
     *
     * @return the value of deposit_product.is_valid
     *
     * @mbggenerated
     */
    public Boolean getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deposit_product.is_valid
     *
     * @param isValid the value for deposit_product.is_valid
     *
     * @mbggenerated
     */
    public void setIsValid(Boolean isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deposit_product.corner_mark_prop
     *
     * @return the value of deposit_product.corner_mark_prop
     *
     * @mbggenerated
     */
    public Byte getCornerMarkProp() {
        return cornerMarkProp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deposit_product.corner_mark_prop
     *
     * @param cornerMarkProp the value for deposit_product.corner_mark_prop
     *
     * @mbggenerated
     */
    public void setCornerMarkProp(Byte cornerMarkProp) {
        this.cornerMarkProp = cornerMarkProp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deposit_product.description
     *
     * @return the value of deposit_product.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deposit_product.description
     *
     * @param description the value for deposit_product.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}