package com.weshare.thunder.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class RecordDepositExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table record_deposit
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table record_deposit
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table record_deposit
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_deposit
     *
     * @mbggenerated
     */
    public RecordDepositExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_deposit
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_deposit
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_deposit
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_deposit
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_deposit
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_deposit
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_deposit
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_deposit
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_deposit
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_deposit
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table record_deposit
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGidIsNull() {
            addCriterion("gid is null");
            return (Criteria) this;
        }

        public Criteria andGidIsNotNull() {
            addCriterion("gid is not null");
            return (Criteria) this;
        }

        public Criteria andGidEqualTo(String value) {
            addCriterion("gid =", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidNotEqualTo(String value) {
            addCriterion("gid <>", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidGreaterThan(String value) {
            addCriterion("gid >", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidGreaterThanOrEqualTo(String value) {
            addCriterion("gid >=", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidLessThan(String value) {
            addCriterion("gid <", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidLessThanOrEqualTo(String value) {
            addCriterion("gid <=", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidLike(String value) {
            addCriterion("gid like", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidNotLike(String value) {
            addCriterion("gid not like", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidIn(List<String> values) {
            addCriterion("gid in", values, "gid");
            return (Criteria) this;
        }

        public Criteria andGidNotIn(List<String> values) {
            addCriterion("gid not in", values, "gid");
            return (Criteria) this;
        }

        public Criteria andGidBetween(String value1, String value2) {
            addCriterion("gid between", value1, value2, "gid");
            return (Criteria) this;
        }

        public Criteria andGidNotBetween(String value1, String value2) {
            addCriterion("gid not between", value1, value2, "gid");
            return (Criteria) this;
        }

        public Criteria andUserGidIsNull() {
            addCriterion("user_gid is null");
            return (Criteria) this;
        }

        public Criteria andUserGidIsNotNull() {
            addCriterion("user_gid is not null");
            return (Criteria) this;
        }

        public Criteria andUserGidEqualTo(String value) {
            addCriterion("user_gid =", value, "userGid");
            return (Criteria) this;
        }

        public Criteria andUserGidNotEqualTo(String value) {
            addCriterion("user_gid <>", value, "userGid");
            return (Criteria) this;
        }

        public Criteria andUserGidGreaterThan(String value) {
            addCriterion("user_gid >", value, "userGid");
            return (Criteria) this;
        }

        public Criteria andUserGidGreaterThanOrEqualTo(String value) {
            addCriterion("user_gid >=", value, "userGid");
            return (Criteria) this;
        }

        public Criteria andUserGidLessThan(String value) {
            addCriterion("user_gid <", value, "userGid");
            return (Criteria) this;
        }

        public Criteria andUserGidLessThanOrEqualTo(String value) {
            addCriterion("user_gid <=", value, "userGid");
            return (Criteria) this;
        }

        public Criteria andUserGidLike(String value) {
            addCriterion("user_gid like", value, "userGid");
            return (Criteria) this;
        }

        public Criteria andUserGidNotLike(String value) {
            addCriterion("user_gid not like", value, "userGid");
            return (Criteria) this;
        }

        public Criteria andUserGidIn(List<String> values) {
            addCriterion("user_gid in", values, "userGid");
            return (Criteria) this;
        }

        public Criteria andUserGidNotIn(List<String> values) {
            addCriterion("user_gid not in", values, "userGid");
            return (Criteria) this;
        }

        public Criteria andUserGidBetween(String value1, String value2) {
            addCriterion("user_gid between", value1, value2, "userGid");
            return (Criteria) this;
        }

        public Criteria andUserGidNotBetween(String value1, String value2) {
            addCriterion("user_gid not between", value1, value2, "userGid");
            return (Criteria) this;
        }

        public Criteria andTransDeductionGidIsNull() {
            addCriterion("trans_deduction_gid is null");
            return (Criteria) this;
        }

        public Criteria andTransDeductionGidIsNotNull() {
            addCriterion("trans_deduction_gid is not null");
            return (Criteria) this;
        }

        public Criteria andTransDeductionGidEqualTo(String value) {
            addCriterion("trans_deduction_gid =", value, "transDeductionGid");
            return (Criteria) this;
        }

        public Criteria andTransDeductionGidNotEqualTo(String value) {
            addCriterion("trans_deduction_gid <>", value, "transDeductionGid");
            return (Criteria) this;
        }

        public Criteria andTransDeductionGidGreaterThan(String value) {
            addCriterion("trans_deduction_gid >", value, "transDeductionGid");
            return (Criteria) this;
        }

        public Criteria andTransDeductionGidGreaterThanOrEqualTo(String value) {
            addCriterion("trans_deduction_gid >=", value, "transDeductionGid");
            return (Criteria) this;
        }

        public Criteria andTransDeductionGidLessThan(String value) {
            addCriterion("trans_deduction_gid <", value, "transDeductionGid");
            return (Criteria) this;
        }

        public Criteria andTransDeductionGidLessThanOrEqualTo(String value) {
            addCriterion("trans_deduction_gid <=", value, "transDeductionGid");
            return (Criteria) this;
        }

        public Criteria andTransDeductionGidLike(String value) {
            addCriterion("trans_deduction_gid like", value, "transDeductionGid");
            return (Criteria) this;
        }

        public Criteria andTransDeductionGidNotLike(String value) {
            addCriterion("trans_deduction_gid not like", value, "transDeductionGid");
            return (Criteria) this;
        }

        public Criteria andTransDeductionGidIn(List<String> values) {
            addCriterion("trans_deduction_gid in", values, "transDeductionGid");
            return (Criteria) this;
        }

        public Criteria andTransDeductionGidNotIn(List<String> values) {
            addCriterion("trans_deduction_gid not in", values, "transDeductionGid");
            return (Criteria) this;
        }

        public Criteria andTransDeductionGidBetween(String value1, String value2) {
            addCriterion("trans_deduction_gid between", value1, value2, "transDeductionGid");
            return (Criteria) this;
        }

        public Criteria andTransDeductionGidNotBetween(String value1, String value2) {
            addCriterion("trans_deduction_gid not between", value1, value2, "transDeductionGid");
            return (Criteria) this;
        }

        public Criteria andDeductCardGidIsNull() {
            addCriterion("deduct_card_gid is null");
            return (Criteria) this;
        }

        public Criteria andDeductCardGidIsNotNull() {
            addCriterion("deduct_card_gid is not null");
            return (Criteria) this;
        }

        public Criteria andDeductCardGidEqualTo(String value) {
            addCriterion("deduct_card_gid =", value, "deductCardGid");
            return (Criteria) this;
        }

        public Criteria andDeductCardGidNotEqualTo(String value) {
            addCriterion("deduct_card_gid <>", value, "deductCardGid");
            return (Criteria) this;
        }

        public Criteria andDeductCardGidGreaterThan(String value) {
            addCriterion("deduct_card_gid >", value, "deductCardGid");
            return (Criteria) this;
        }

        public Criteria andDeductCardGidGreaterThanOrEqualTo(String value) {
            addCriterion("deduct_card_gid >=", value, "deductCardGid");
            return (Criteria) this;
        }

        public Criteria andDeductCardGidLessThan(String value) {
            addCriterion("deduct_card_gid <", value, "deductCardGid");
            return (Criteria) this;
        }

        public Criteria andDeductCardGidLessThanOrEqualTo(String value) {
            addCriterion("deduct_card_gid <=", value, "deductCardGid");
            return (Criteria) this;
        }

        public Criteria andDeductCardGidLike(String value) {
            addCriterion("deduct_card_gid like", value, "deductCardGid");
            return (Criteria) this;
        }

        public Criteria andDeductCardGidNotLike(String value) {
            addCriterion("deduct_card_gid not like", value, "deductCardGid");
            return (Criteria) this;
        }

        public Criteria andDeductCardGidIn(List<String> values) {
            addCriterion("deduct_card_gid in", values, "deductCardGid");
            return (Criteria) this;
        }

        public Criteria andDeductCardGidNotIn(List<String> values) {
            addCriterion("deduct_card_gid not in", values, "deductCardGid");
            return (Criteria) this;
        }

        public Criteria andDeductCardGidBetween(String value1, String value2) {
            addCriterion("deduct_card_gid between", value1, value2, "deductCardGid");
            return (Criteria) this;
        }

        public Criteria andDeductCardGidNotBetween(String value1, String value2) {
            addCriterion("deduct_card_gid not between", value1, value2, "deductCardGid");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Integer value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Integer value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Integer value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Integer value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Integer value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Integer> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Integer> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Integer value1, Integer value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Integer value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Integer value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Integer value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Integer value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Integer value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Integer> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Integer> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Integer value1, Integer value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andDepositPeriodIsNull() {
            addCriterion("deposit_period is null");
            return (Criteria) this;
        }

        public Criteria andDepositPeriodIsNotNull() {
            addCriterion("deposit_period is not null");
            return (Criteria) this;
        }

        public Criteria andDepositPeriodEqualTo(Integer value) {
            addCriterion("deposit_period =", value, "depositPeriod");
            return (Criteria) this;
        }

        public Criteria andDepositPeriodNotEqualTo(Integer value) {
            addCriterion("deposit_period <>", value, "depositPeriod");
            return (Criteria) this;
        }

        public Criteria andDepositPeriodGreaterThan(Integer value) {
            addCriterion("deposit_period >", value, "depositPeriod");
            return (Criteria) this;
        }

        public Criteria andDepositPeriodGreaterThanOrEqualTo(Integer value) {
            addCriterion("deposit_period >=", value, "depositPeriod");
            return (Criteria) this;
        }

        public Criteria andDepositPeriodLessThan(Integer value) {
            addCriterion("deposit_period <", value, "depositPeriod");
            return (Criteria) this;
        }

        public Criteria andDepositPeriodLessThanOrEqualTo(Integer value) {
            addCriterion("deposit_period <=", value, "depositPeriod");
            return (Criteria) this;
        }

        public Criteria andDepositPeriodIn(List<Integer> values) {
            addCriterion("deposit_period in", values, "depositPeriod");
            return (Criteria) this;
        }

        public Criteria andDepositPeriodNotIn(List<Integer> values) {
            addCriterion("deposit_period not in", values, "depositPeriod");
            return (Criteria) this;
        }

        public Criteria andDepositPeriodBetween(Integer value1, Integer value2) {
            addCriterion("deposit_period between", value1, value2, "depositPeriod");
            return (Criteria) this;
        }

        public Criteria andDepositPeriodNotBetween(Integer value1, Integer value2) {
            addCriterion("deposit_period not between", value1, value2, "depositPeriod");
            return (Criteria) this;
        }

        public Criteria andDepositRateIsNull() {
            addCriterion("deposit_rate is null");
            return (Criteria) this;
        }

        public Criteria andDepositRateIsNotNull() {
            addCriterion("deposit_rate is not null");
            return (Criteria) this;
        }

        public Criteria andDepositRateEqualTo(BigDecimal value) {
            addCriterion("deposit_rate =", value, "depositRate");
            return (Criteria) this;
        }

        public Criteria andDepositRateNotEqualTo(BigDecimal value) {
            addCriterion("deposit_rate <>", value, "depositRate");
            return (Criteria) this;
        }

        public Criteria andDepositRateGreaterThan(BigDecimal value) {
            addCriterion("deposit_rate >", value, "depositRate");
            return (Criteria) this;
        }

        public Criteria andDepositRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("deposit_rate >=", value, "depositRate");
            return (Criteria) this;
        }

        public Criteria andDepositRateLessThan(BigDecimal value) {
            addCriterion("deposit_rate <", value, "depositRate");
            return (Criteria) this;
        }

        public Criteria andDepositRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("deposit_rate <=", value, "depositRate");
            return (Criteria) this;
        }

        public Criteria andDepositRateIn(List<BigDecimal> values) {
            addCriterion("deposit_rate in", values, "depositRate");
            return (Criteria) this;
        }

        public Criteria andDepositRateNotIn(List<BigDecimal> values) {
            addCriterion("deposit_rate not in", values, "depositRate");
            return (Criteria) this;
        }

        public Criteria andDepositRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("deposit_rate between", value1, value2, "depositRate");
            return (Criteria) this;
        }

        public Criteria andDepositRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("deposit_rate not between", value1, value2, "depositRate");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNull() {
            addCriterion("product_id is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("product_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(Integer value) {
            addCriterion("product_id =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(Integer value) {
            addCriterion("product_id <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(Integer value) {
            addCriterion("product_id >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("product_id >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(Integer value) {
            addCriterion("product_id <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(Integer value) {
            addCriterion("product_id <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<Integer> values) {
            addCriterion("product_id in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<Integer> values) {
            addCriterion("product_id not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(Integer value1, Integer value2) {
            addCriterion("product_id between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(Integer value1, Integer value2) {
            addCriterion("product_id not between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andAmountInitialIsNull() {
            addCriterion("amount_initial is null");
            return (Criteria) this;
        }

        public Criteria andAmountInitialIsNotNull() {
            addCriterion("amount_initial is not null");
            return (Criteria) this;
        }

        public Criteria andAmountInitialEqualTo(BigDecimal value) {
            addCriterion("amount_initial =", value, "amountInitial");
            return (Criteria) this;
        }

        public Criteria andAmountInitialNotEqualTo(BigDecimal value) {
            addCriterion("amount_initial <>", value, "amountInitial");
            return (Criteria) this;
        }

        public Criteria andAmountInitialGreaterThan(BigDecimal value) {
            addCriterion("amount_initial >", value, "amountInitial");
            return (Criteria) this;
        }

        public Criteria andAmountInitialGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("amount_initial >=", value, "amountInitial");
            return (Criteria) this;
        }

        public Criteria andAmountInitialLessThan(BigDecimal value) {
            addCriterion("amount_initial <", value, "amountInitial");
            return (Criteria) this;
        }

        public Criteria andAmountInitialLessThanOrEqualTo(BigDecimal value) {
            addCriterion("amount_initial <=", value, "amountInitial");
            return (Criteria) this;
        }

        public Criteria andAmountInitialIn(List<BigDecimal> values) {
            addCriterion("amount_initial in", values, "amountInitial");
            return (Criteria) this;
        }

        public Criteria andAmountInitialNotIn(List<BigDecimal> values) {
            addCriterion("amount_initial not in", values, "amountInitial");
            return (Criteria) this;
        }

        public Criteria andAmountInitialBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("amount_initial between", value1, value2, "amountInitial");
            return (Criteria) this;
        }

        public Criteria andAmountInitialNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("amount_initial not between", value1, value2, "amountInitial");
            return (Criteria) this;
        }

        public Criteria andAmountDepositIsNull() {
            addCriterion("amount_deposit is null");
            return (Criteria) this;
        }

        public Criteria andAmountDepositIsNotNull() {
            addCriterion("amount_deposit is not null");
            return (Criteria) this;
        }

        public Criteria andAmountDepositEqualTo(BigDecimal value) {
            addCriterion("amount_deposit =", value, "amountDeposit");
            return (Criteria) this;
        }

        public Criteria andAmountDepositNotEqualTo(BigDecimal value) {
            addCriterion("amount_deposit <>", value, "amountDeposit");
            return (Criteria) this;
        }

        public Criteria andAmountDepositGreaterThan(BigDecimal value) {
            addCriterion("amount_deposit >", value, "amountDeposit");
            return (Criteria) this;
        }

        public Criteria andAmountDepositGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("amount_deposit >=", value, "amountDeposit");
            return (Criteria) this;
        }

        public Criteria andAmountDepositLessThan(BigDecimal value) {
            addCriterion("amount_deposit <", value, "amountDeposit");
            return (Criteria) this;
        }

        public Criteria andAmountDepositLessThanOrEqualTo(BigDecimal value) {
            addCriterion("amount_deposit <=", value, "amountDeposit");
            return (Criteria) this;
        }

        public Criteria andAmountDepositIn(List<BigDecimal> values) {
            addCriterion("amount_deposit in", values, "amountDeposit");
            return (Criteria) this;
        }

        public Criteria andAmountDepositNotIn(List<BigDecimal> values) {
            addCriterion("amount_deposit not in", values, "amountDeposit");
            return (Criteria) this;
        }

        public Criteria andAmountDepositBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("amount_deposit between", value1, value2, "amountDeposit");
            return (Criteria) this;
        }

        public Criteria andAmountDepositNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("amount_deposit not between", value1, value2, "amountDeposit");
            return (Criteria) this;
        }

        public Criteria andDepositStateIsNull() {
            addCriterion("deposit_state is null");
            return (Criteria) this;
        }

        public Criteria andDepositStateIsNotNull() {
            addCriterion("deposit_state is not null");
            return (Criteria) this;
        }

        public Criteria andDepositStateEqualTo(Byte value) {
            addCriterion("deposit_state =", value, "depositState");
            return (Criteria) this;
        }

        public Criteria andDepositStateNotEqualTo(Byte value) {
            addCriterion("deposit_state <>", value, "depositState");
            return (Criteria) this;
        }

        public Criteria andDepositStateGreaterThan(Byte value) {
            addCriterion("deposit_state >", value, "depositState");
            return (Criteria) this;
        }

        public Criteria andDepositStateGreaterThanOrEqualTo(Byte value) {
            addCriterion("deposit_state >=", value, "depositState");
            return (Criteria) this;
        }

        public Criteria andDepositStateLessThan(Byte value) {
            addCriterion("deposit_state <", value, "depositState");
            return (Criteria) this;
        }

        public Criteria andDepositStateLessThanOrEqualTo(Byte value) {
            addCriterion("deposit_state <=", value, "depositState");
            return (Criteria) this;
        }

        public Criteria andDepositStateIn(List<Byte> values) {
            addCriterion("deposit_state in", values, "depositState");
            return (Criteria) this;
        }

        public Criteria andDepositStateNotIn(List<Byte> values) {
            addCriterion("deposit_state not in", values, "depositState");
            return (Criteria) this;
        }

        public Criteria andDepositStateBetween(Byte value1, Byte value2) {
            addCriterion("deposit_state between", value1, value2, "depositState");
            return (Criteria) this;
        }

        public Criteria andDepositStateNotBetween(Byte value1, Byte value2) {
            addCriterion("deposit_state not between", value1, value2, "depositState");
            return (Criteria) this;
        }

        public Criteria andDepositSrcIsNull() {
            addCriterion("deposit_src is null");
            return (Criteria) this;
        }

        public Criteria andDepositSrcIsNotNull() {
            addCriterion("deposit_src is not null");
            return (Criteria) this;
        }

        public Criteria andDepositSrcEqualTo(Byte value) {
            addCriterion("deposit_src =", value, "depositSrc");
            return (Criteria) this;
        }

        public Criteria andDepositSrcNotEqualTo(Byte value) {
            addCriterion("deposit_src <>", value, "depositSrc");
            return (Criteria) this;
        }

        public Criteria andDepositSrcGreaterThan(Byte value) {
            addCriterion("deposit_src >", value, "depositSrc");
            return (Criteria) this;
        }

        public Criteria andDepositSrcGreaterThanOrEqualTo(Byte value) {
            addCriterion("deposit_src >=", value, "depositSrc");
            return (Criteria) this;
        }

        public Criteria andDepositSrcLessThan(Byte value) {
            addCriterion("deposit_src <", value, "depositSrc");
            return (Criteria) this;
        }

        public Criteria andDepositSrcLessThanOrEqualTo(Byte value) {
            addCriterion("deposit_src <=", value, "depositSrc");
            return (Criteria) this;
        }

        public Criteria andDepositSrcIn(List<Byte> values) {
            addCriterion("deposit_src in", values, "depositSrc");
            return (Criteria) this;
        }

        public Criteria andDepositSrcNotIn(List<Byte> values) {
            addCriterion("deposit_src not in", values, "depositSrc");
            return (Criteria) this;
        }

        public Criteria andDepositSrcBetween(Byte value1, Byte value2) {
            addCriterion("deposit_src between", value1, value2, "depositSrc");
            return (Criteria) this;
        }

        public Criteria andDepositSrcNotBetween(Byte value1, Byte value2) {
            addCriterion("deposit_src not between", value1, value2, "depositSrc");
            return (Criteria) this;
        }

        public Criteria andDepositTypeIsNull() {
            addCriterion("deposit_type is null");
            return (Criteria) this;
        }

        public Criteria andDepositTypeIsNotNull() {
            addCriterion("deposit_type is not null");
            return (Criteria) this;
        }

        public Criteria andDepositTypeEqualTo(Byte value) {
            addCriterion("deposit_type =", value, "depositType");
            return (Criteria) this;
        }

        public Criteria andDepositTypeNotEqualTo(Byte value) {
            addCriterion("deposit_type <>", value, "depositType");
            return (Criteria) this;
        }

        public Criteria andDepositTypeGreaterThan(Byte value) {
            addCriterion("deposit_type >", value, "depositType");
            return (Criteria) this;
        }

        public Criteria andDepositTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("deposit_type >=", value, "depositType");
            return (Criteria) this;
        }

        public Criteria andDepositTypeLessThan(Byte value) {
            addCriterion("deposit_type <", value, "depositType");
            return (Criteria) this;
        }

        public Criteria andDepositTypeLessThanOrEqualTo(Byte value) {
            addCriterion("deposit_type <=", value, "depositType");
            return (Criteria) this;
        }

        public Criteria andDepositTypeIn(List<Byte> values) {
            addCriterion("deposit_type in", values, "depositType");
            return (Criteria) this;
        }

        public Criteria andDepositTypeNotIn(List<Byte> values) {
            addCriterion("deposit_type not in", values, "depositType");
            return (Criteria) this;
        }

        public Criteria andDepositTypeBetween(Byte value1, Byte value2) {
            addCriterion("deposit_type between", value1, value2, "depositType");
            return (Criteria) this;
        }

        public Criteria andDepositTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("deposit_type not between", value1, value2, "depositType");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Integer value) {
            addCriterion("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Integer value) {
            addCriterion("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Integer value) {
            addCriterion("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Integer value) {
            addCriterion("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Integer value) {
            addCriterion("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Integer> values) {
            addCriterion("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Integer> values) {
            addCriterion("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Integer value1, Integer value2) {
            addCriterion("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andRealEarningIsNull() {
            addCriterion("real_earning is null");
            return (Criteria) this;
        }

        public Criteria andRealEarningIsNotNull() {
            addCriterion("real_earning is not null");
            return (Criteria) this;
        }

        public Criteria andRealEarningEqualTo(BigDecimal value) {
            addCriterion("real_earning =", value, "realEarning");
            return (Criteria) this;
        }

        public Criteria andRealEarningNotEqualTo(BigDecimal value) {
            addCriterion("real_earning <>", value, "realEarning");
            return (Criteria) this;
        }

        public Criteria andRealEarningGreaterThan(BigDecimal value) {
            addCriterion("real_earning >", value, "realEarning");
            return (Criteria) this;
        }

        public Criteria andRealEarningGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("real_earning >=", value, "realEarning");
            return (Criteria) this;
        }

        public Criteria andRealEarningLessThan(BigDecimal value) {
            addCriterion("real_earning <", value, "realEarning");
            return (Criteria) this;
        }

        public Criteria andRealEarningLessThanOrEqualTo(BigDecimal value) {
            addCriterion("real_earning <=", value, "realEarning");
            return (Criteria) this;
        }

        public Criteria andRealEarningIn(List<BigDecimal> values) {
            addCriterion("real_earning in", values, "realEarning");
            return (Criteria) this;
        }

        public Criteria andRealEarningNotIn(List<BigDecimal> values) {
            addCriterion("real_earning not in", values, "realEarning");
            return (Criteria) this;
        }

        public Criteria andRealEarningBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("real_earning between", value1, value2, "realEarning");
            return (Criteria) this;
        }

        public Criteria andRealEarningNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("real_earning not between", value1, value2, "realEarning");
            return (Criteria) this;
        }

        public Criteria andLeftEarningIsNull() {
            addCriterion("left_earning is null");
            return (Criteria) this;
        }

        public Criteria andLeftEarningIsNotNull() {
            addCriterion("left_earning is not null");
            return (Criteria) this;
        }

        public Criteria andLeftEarningEqualTo(BigDecimal value) {
            addCriterion("left_earning =", value, "leftEarning");
            return (Criteria) this;
        }

        public Criteria andLeftEarningNotEqualTo(BigDecimal value) {
            addCriterion("left_earning <>", value, "leftEarning");
            return (Criteria) this;
        }

        public Criteria andLeftEarningGreaterThan(BigDecimal value) {
            addCriterion("left_earning >", value, "leftEarning");
            return (Criteria) this;
        }

        public Criteria andLeftEarningGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("left_earning >=", value, "leftEarning");
            return (Criteria) this;
        }

        public Criteria andLeftEarningLessThan(BigDecimal value) {
            addCriterion("left_earning <", value, "leftEarning");
            return (Criteria) this;
        }

        public Criteria andLeftEarningLessThanOrEqualTo(BigDecimal value) {
            addCriterion("left_earning <=", value, "leftEarning");
            return (Criteria) this;
        }

        public Criteria andLeftEarningIn(List<BigDecimal> values) {
            addCriterion("left_earning in", values, "leftEarning");
            return (Criteria) this;
        }

        public Criteria andLeftEarningNotIn(List<BigDecimal> values) {
            addCriterion("left_earning not in", values, "leftEarning");
            return (Criteria) this;
        }

        public Criteria andLeftEarningBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("left_earning between", value1, value2, "leftEarning");
            return (Criteria) this;
        }

        public Criteria andLeftEarningNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("left_earning not between", value1, value2, "leftEarning");
            return (Criteria) this;
        }

        public Criteria andFailReasonIsNull() {
            addCriterion("fail_reason is null");
            return (Criteria) this;
        }

        public Criteria andFailReasonIsNotNull() {
            addCriterion("fail_reason is not null");
            return (Criteria) this;
        }

        public Criteria andFailReasonEqualTo(String value) {
            addCriterion("fail_reason =", value, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonNotEqualTo(String value) {
            addCriterion("fail_reason <>", value, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonGreaterThan(String value) {
            addCriterion("fail_reason >", value, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonGreaterThanOrEqualTo(String value) {
            addCriterion("fail_reason >=", value, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonLessThan(String value) {
            addCriterion("fail_reason <", value, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonLessThanOrEqualTo(String value) {
            addCriterion("fail_reason <=", value, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonLike(String value) {
            addCriterion("fail_reason like", value, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonNotLike(String value) {
            addCriterion("fail_reason not like", value, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonIn(List<String> values) {
            addCriterion("fail_reason in", values, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonNotIn(List<String> values) {
            addCriterion("fail_reason not in", values, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonBetween(String value1, String value2) {
            addCriterion("fail_reason between", value1, value2, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonNotBetween(String value1, String value2) {
            addCriterion("fail_reason not between", value1, value2, "failReason");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(String value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(String value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(String value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(String value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(String value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLike(String value) {
            addCriterion("order_id like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotLike(String value) {
            addCriterion("order_id not like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<String> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<String> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(String value1, String value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(String value1, String value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table record_deposit
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table record_deposit
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}