package com.weshare.thunder.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class TransWithdrawExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trans_withdraw
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trans_withdraw
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trans_withdraw
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_withdraw
     *
     * @mbggenerated
     */
    public TransWithdrawExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_withdraw
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_withdraw
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_withdraw
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_withdraw
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_withdraw
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_withdraw
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_withdraw
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_withdraw
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_withdraw
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_withdraw
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table trans_withdraw
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGidIsNull() {
            addCriterion("gid is null");
            return (Criteria) this;
        }

        public Criteria andGidIsNotNull() {
            addCriterion("gid is not null");
            return (Criteria) this;
        }

        public Criteria andGidEqualTo(String value) {
            addCriterion("gid =", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidNotEqualTo(String value) {
            addCriterion("gid <>", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidGreaterThan(String value) {
            addCriterion("gid >", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidGreaterThanOrEqualTo(String value) {
            addCriterion("gid >=", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidLessThan(String value) {
            addCriterion("gid <", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidLessThanOrEqualTo(String value) {
            addCriterion("gid <=", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidLike(String value) {
            addCriterion("gid like", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidNotLike(String value) {
            addCriterion("gid not like", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidIn(List<String> values) {
            addCriterion("gid in", values, "gid");
            return (Criteria) this;
        }

        public Criteria andGidNotIn(List<String> values) {
            addCriterion("gid not in", values, "gid");
            return (Criteria) this;
        }

        public Criteria andGidBetween(String value1, String value2) {
            addCriterion("gid between", value1, value2, "gid");
            return (Criteria) this;
        }

        public Criteria andGidNotBetween(String value1, String value2) {
            addCriterion("gid not between", value1, value2, "gid");
            return (Criteria) this;
        }

        public Criteria andUserGidIsNull() {
            addCriterion("user_gid is null");
            return (Criteria) this;
        }

        public Criteria andUserGidIsNotNull() {
            addCriterion("user_gid is not null");
            return (Criteria) this;
        }

        public Criteria andUserGidEqualTo(String value) {
            addCriterion("user_gid =", value, "userGid");
            return (Criteria) this;
        }

        public Criteria andUserGidNotEqualTo(String value) {
            addCriterion("user_gid <>", value, "userGid");
            return (Criteria) this;
        }

        public Criteria andUserGidGreaterThan(String value) {
            addCriterion("user_gid >", value, "userGid");
            return (Criteria) this;
        }

        public Criteria andUserGidGreaterThanOrEqualTo(String value) {
            addCriterion("user_gid >=", value, "userGid");
            return (Criteria) this;
        }

        public Criteria andUserGidLessThan(String value) {
            addCriterion("user_gid <", value, "userGid");
            return (Criteria) this;
        }

        public Criteria andUserGidLessThanOrEqualTo(String value) {
            addCriterion("user_gid <=", value, "userGid");
            return (Criteria) this;
        }

        public Criteria andUserGidLike(String value) {
            addCriterion("user_gid like", value, "userGid");
            return (Criteria) this;
        }

        public Criteria andUserGidNotLike(String value) {
            addCriterion("user_gid not like", value, "userGid");
            return (Criteria) this;
        }

        public Criteria andUserGidIn(List<String> values) {
            addCriterion("user_gid in", values, "userGid");
            return (Criteria) this;
        }

        public Criteria andUserGidNotIn(List<String> values) {
            addCriterion("user_gid not in", values, "userGid");
            return (Criteria) this;
        }

        public Criteria andUserGidBetween(String value1, String value2) {
            addCriterion("user_gid between", value1, value2, "userGid");
            return (Criteria) this;
        }

        public Criteria andUserGidNotBetween(String value1, String value2) {
            addCriterion("user_gid not between", value1, value2, "userGid");
            return (Criteria) this;
        }

        public Criteria andWithdrawCardGidIsNull() {
            addCriterion("withdraw_card_gid is null");
            return (Criteria) this;
        }

        public Criteria andWithdrawCardGidIsNotNull() {
            addCriterion("withdraw_card_gid is not null");
            return (Criteria) this;
        }

        public Criteria andWithdrawCardGidEqualTo(String value) {
            addCriterion("withdraw_card_gid =", value, "withdrawCardGid");
            return (Criteria) this;
        }

        public Criteria andWithdrawCardGidNotEqualTo(String value) {
            addCriterion("withdraw_card_gid <>", value, "withdrawCardGid");
            return (Criteria) this;
        }

        public Criteria andWithdrawCardGidGreaterThan(String value) {
            addCriterion("withdraw_card_gid >", value, "withdrawCardGid");
            return (Criteria) this;
        }

        public Criteria andWithdrawCardGidGreaterThanOrEqualTo(String value) {
            addCriterion("withdraw_card_gid >=", value, "withdrawCardGid");
            return (Criteria) this;
        }

        public Criteria andWithdrawCardGidLessThan(String value) {
            addCriterion("withdraw_card_gid <", value, "withdrawCardGid");
            return (Criteria) this;
        }

        public Criteria andWithdrawCardGidLessThanOrEqualTo(String value) {
            addCriterion("withdraw_card_gid <=", value, "withdrawCardGid");
            return (Criteria) this;
        }

        public Criteria andWithdrawCardGidLike(String value) {
            addCriterion("withdraw_card_gid like", value, "withdrawCardGid");
            return (Criteria) this;
        }

        public Criteria andWithdrawCardGidNotLike(String value) {
            addCriterion("withdraw_card_gid not like", value, "withdrawCardGid");
            return (Criteria) this;
        }

        public Criteria andWithdrawCardGidIn(List<String> values) {
            addCriterion("withdraw_card_gid in", values, "withdrawCardGid");
            return (Criteria) this;
        }

        public Criteria andWithdrawCardGidNotIn(List<String> values) {
            addCriterion("withdraw_card_gid not in", values, "withdrawCardGid");
            return (Criteria) this;
        }

        public Criteria andWithdrawCardGidBetween(String value1, String value2) {
            addCriterion("withdraw_card_gid between", value1, value2, "withdrawCardGid");
            return (Criteria) this;
        }

        public Criteria andWithdrawCardGidNotBetween(String value1, String value2) {
            addCriterion("withdraw_card_gid not between", value1, value2, "withdrawCardGid");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Integer value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Integer value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Integer value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Integer value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Integer value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Integer> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Integer> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Integer value1, Integer value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Integer value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Integer value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Integer value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Integer value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Integer value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Integer> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Integer> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Integer value1, Integer value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andRecordWithdrawAnytimeGidIsNull() {
            addCriterion("record_withdraw_anytime_gid is null");
            return (Criteria) this;
        }

        public Criteria andRecordWithdrawAnytimeGidIsNotNull() {
            addCriterion("record_withdraw_anytime_gid is not null");
            return (Criteria) this;
        }

        public Criteria andRecordWithdrawAnytimeGidEqualTo(String value) {
            addCriterion("record_withdraw_anytime_gid =", value, "recordWithdrawAnytimeGid");
            return (Criteria) this;
        }

        public Criteria andRecordWithdrawAnytimeGidNotEqualTo(String value) {
            addCriterion("record_withdraw_anytime_gid <>", value, "recordWithdrawAnytimeGid");
            return (Criteria) this;
        }

        public Criteria andRecordWithdrawAnytimeGidGreaterThan(String value) {
            addCriterion("record_withdraw_anytime_gid >", value, "recordWithdrawAnytimeGid");
            return (Criteria) this;
        }

        public Criteria andRecordWithdrawAnytimeGidGreaterThanOrEqualTo(String value) {
            addCriterion("record_withdraw_anytime_gid >=", value, "recordWithdrawAnytimeGid");
            return (Criteria) this;
        }

        public Criteria andRecordWithdrawAnytimeGidLessThan(String value) {
            addCriterion("record_withdraw_anytime_gid <", value, "recordWithdrawAnytimeGid");
            return (Criteria) this;
        }

        public Criteria andRecordWithdrawAnytimeGidLessThanOrEqualTo(String value) {
            addCriterion("record_withdraw_anytime_gid <=", value, "recordWithdrawAnytimeGid");
            return (Criteria) this;
        }

        public Criteria andRecordWithdrawAnytimeGidLike(String value) {
            addCriterion("record_withdraw_anytime_gid like", value, "recordWithdrawAnytimeGid");
            return (Criteria) this;
        }

        public Criteria andRecordWithdrawAnytimeGidNotLike(String value) {
            addCriterion("record_withdraw_anytime_gid not like", value, "recordWithdrawAnytimeGid");
            return (Criteria) this;
        }

        public Criteria andRecordWithdrawAnytimeGidIn(List<String> values) {
            addCriterion("record_withdraw_anytime_gid in", values, "recordWithdrawAnytimeGid");
            return (Criteria) this;
        }

        public Criteria andRecordWithdrawAnytimeGidNotIn(List<String> values) {
            addCriterion("record_withdraw_anytime_gid not in", values, "recordWithdrawAnytimeGid");
            return (Criteria) this;
        }

        public Criteria andRecordWithdrawAnytimeGidBetween(String value1, String value2) {
            addCriterion("record_withdraw_anytime_gid between", value1, value2, "recordWithdrawAnytimeGid");
            return (Criteria) this;
        }

        public Criteria andRecordWithdrawAnytimeGidNotBetween(String value1, String value2) {
            addCriterion("record_withdraw_anytime_gid not between", value1, value2, "recordWithdrawAnytimeGid");
            return (Criteria) this;
        }

        public Criteria andWithdrawAmountIsNull() {
            addCriterion("withdraw_amount is null");
            return (Criteria) this;
        }

        public Criteria andWithdrawAmountIsNotNull() {
            addCriterion("withdraw_amount is not null");
            return (Criteria) this;
        }

        public Criteria andWithdrawAmountEqualTo(BigDecimal value) {
            addCriterion("withdraw_amount =", value, "withdrawAmount");
            return (Criteria) this;
        }

        public Criteria andWithdrawAmountNotEqualTo(BigDecimal value) {
            addCriterion("withdraw_amount <>", value, "withdrawAmount");
            return (Criteria) this;
        }

        public Criteria andWithdrawAmountGreaterThan(BigDecimal value) {
            addCriterion("withdraw_amount >", value, "withdrawAmount");
            return (Criteria) this;
        }

        public Criteria andWithdrawAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("withdraw_amount >=", value, "withdrawAmount");
            return (Criteria) this;
        }

        public Criteria andWithdrawAmountLessThan(BigDecimal value) {
            addCriterion("withdraw_amount <", value, "withdrawAmount");
            return (Criteria) this;
        }

        public Criteria andWithdrawAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("withdraw_amount <=", value, "withdrawAmount");
            return (Criteria) this;
        }

        public Criteria andWithdrawAmountIn(List<BigDecimal> values) {
            addCriterion("withdraw_amount in", values, "withdrawAmount");
            return (Criteria) this;
        }

        public Criteria andWithdrawAmountNotIn(List<BigDecimal> values) {
            addCriterion("withdraw_amount not in", values, "withdrawAmount");
            return (Criteria) this;
        }

        public Criteria andWithdrawAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("withdraw_amount between", value1, value2, "withdrawAmount");
            return (Criteria) this;
        }

        public Criteria andWithdrawAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("withdraw_amount not between", value1, value2, "withdrawAmount");
            return (Criteria) this;
        }

        public Criteria andWithdrawCapitalIsNull() {
            addCriterion("withdraw_capital is null");
            return (Criteria) this;
        }

        public Criteria andWithdrawCapitalIsNotNull() {
            addCriterion("withdraw_capital is not null");
            return (Criteria) this;
        }

        public Criteria andWithdrawCapitalEqualTo(BigDecimal value) {
            addCriterion("withdraw_capital =", value, "withdrawCapital");
            return (Criteria) this;
        }

        public Criteria andWithdrawCapitalNotEqualTo(BigDecimal value) {
            addCriterion("withdraw_capital <>", value, "withdrawCapital");
            return (Criteria) this;
        }

        public Criteria andWithdrawCapitalGreaterThan(BigDecimal value) {
            addCriterion("withdraw_capital >", value, "withdrawCapital");
            return (Criteria) this;
        }

        public Criteria andWithdrawCapitalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("withdraw_capital >=", value, "withdrawCapital");
            return (Criteria) this;
        }

        public Criteria andWithdrawCapitalLessThan(BigDecimal value) {
            addCriterion("withdraw_capital <", value, "withdrawCapital");
            return (Criteria) this;
        }

        public Criteria andWithdrawCapitalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("withdraw_capital <=", value, "withdrawCapital");
            return (Criteria) this;
        }

        public Criteria andWithdrawCapitalIn(List<BigDecimal> values) {
            addCriterion("withdraw_capital in", values, "withdrawCapital");
            return (Criteria) this;
        }

        public Criteria andWithdrawCapitalNotIn(List<BigDecimal> values) {
            addCriterion("withdraw_capital not in", values, "withdrawCapital");
            return (Criteria) this;
        }

        public Criteria andWithdrawCapitalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("withdraw_capital between", value1, value2, "withdrawCapital");
            return (Criteria) this;
        }

        public Criteria andWithdrawCapitalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("withdraw_capital not between", value1, value2, "withdrawCapital");
            return (Criteria) this;
        }

        public Criteria andWithdrawEarningIsNull() {
            addCriterion("withdraw_earning is null");
            return (Criteria) this;
        }

        public Criteria andWithdrawEarningIsNotNull() {
            addCriterion("withdraw_earning is not null");
            return (Criteria) this;
        }

        public Criteria andWithdrawEarningEqualTo(BigDecimal value) {
            addCriterion("withdraw_earning =", value, "withdrawEarning");
            return (Criteria) this;
        }

        public Criteria andWithdrawEarningNotEqualTo(BigDecimal value) {
            addCriterion("withdraw_earning <>", value, "withdrawEarning");
            return (Criteria) this;
        }

        public Criteria andWithdrawEarningGreaterThan(BigDecimal value) {
            addCriterion("withdraw_earning >", value, "withdrawEarning");
            return (Criteria) this;
        }

        public Criteria andWithdrawEarningGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("withdraw_earning >=", value, "withdrawEarning");
            return (Criteria) this;
        }

        public Criteria andWithdrawEarningLessThan(BigDecimal value) {
            addCriterion("withdraw_earning <", value, "withdrawEarning");
            return (Criteria) this;
        }

        public Criteria andWithdrawEarningLessThanOrEqualTo(BigDecimal value) {
            addCriterion("withdraw_earning <=", value, "withdrawEarning");
            return (Criteria) this;
        }

        public Criteria andWithdrawEarningIn(List<BigDecimal> values) {
            addCriterion("withdraw_earning in", values, "withdrawEarning");
            return (Criteria) this;
        }

        public Criteria andWithdrawEarningNotIn(List<BigDecimal> values) {
            addCriterion("withdraw_earning not in", values, "withdrawEarning");
            return (Criteria) this;
        }

        public Criteria andWithdrawEarningBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("withdraw_earning between", value1, value2, "withdrawEarning");
            return (Criteria) this;
        }

        public Criteria andWithdrawEarningNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("withdraw_earning not between", value1, value2, "withdrawEarning");
            return (Criteria) this;
        }

        public Criteria andWithdrawFromnogainsIsNull() {
            addCriterion("withdraw_fromnogains is null");
            return (Criteria) this;
        }

        public Criteria andWithdrawFromnogainsIsNotNull() {
            addCriterion("withdraw_fromnogains is not null");
            return (Criteria) this;
        }

        public Criteria andWithdrawFromnogainsEqualTo(BigDecimal value) {
            addCriterion("withdraw_fromnogains =", value, "withdrawFromnogains");
            return (Criteria) this;
        }

        public Criteria andWithdrawFromnogainsNotEqualTo(BigDecimal value) {
            addCriterion("withdraw_fromnogains <>", value, "withdrawFromnogains");
            return (Criteria) this;
        }

        public Criteria andWithdrawFromnogainsGreaterThan(BigDecimal value) {
            addCriterion("withdraw_fromnogains >", value, "withdrawFromnogains");
            return (Criteria) this;
        }

        public Criteria andWithdrawFromnogainsGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("withdraw_fromnogains >=", value, "withdrawFromnogains");
            return (Criteria) this;
        }

        public Criteria andWithdrawFromnogainsLessThan(BigDecimal value) {
            addCriterion("withdraw_fromnogains <", value, "withdrawFromnogains");
            return (Criteria) this;
        }

        public Criteria andWithdrawFromnogainsLessThanOrEqualTo(BigDecimal value) {
            addCriterion("withdraw_fromnogains <=", value, "withdrawFromnogains");
            return (Criteria) this;
        }

        public Criteria andWithdrawFromnogainsIn(List<BigDecimal> values) {
            addCriterion("withdraw_fromnogains in", values, "withdrawFromnogains");
            return (Criteria) this;
        }

        public Criteria andWithdrawFromnogainsNotIn(List<BigDecimal> values) {
            addCriterion("withdraw_fromnogains not in", values, "withdrawFromnogains");
            return (Criteria) this;
        }

        public Criteria andWithdrawFromnogainsBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("withdraw_fromnogains between", value1, value2, "withdrawFromnogains");
            return (Criteria) this;
        }

        public Criteria andWithdrawFromnogainsNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("withdraw_fromnogains not between", value1, value2, "withdrawFromnogains");
            return (Criteria) this;
        }

        public Criteria andWithdrawFromfundIsNull() {
            addCriterion("withdraw_fromfund is null");
            return (Criteria) this;
        }

        public Criteria andWithdrawFromfundIsNotNull() {
            addCriterion("withdraw_fromfund is not null");
            return (Criteria) this;
        }

        public Criteria andWithdrawFromfundEqualTo(BigDecimal value) {
            addCriterion("withdraw_fromfund =", value, "withdrawFromfund");
            return (Criteria) this;
        }

        public Criteria andWithdrawFromfundNotEqualTo(BigDecimal value) {
            addCriterion("withdraw_fromfund <>", value, "withdrawFromfund");
            return (Criteria) this;
        }

        public Criteria andWithdrawFromfundGreaterThan(BigDecimal value) {
            addCriterion("withdraw_fromfund >", value, "withdrawFromfund");
            return (Criteria) this;
        }

        public Criteria andWithdrawFromfundGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("withdraw_fromfund >=", value, "withdrawFromfund");
            return (Criteria) this;
        }

        public Criteria andWithdrawFromfundLessThan(BigDecimal value) {
            addCriterion("withdraw_fromfund <", value, "withdrawFromfund");
            return (Criteria) this;
        }

        public Criteria andWithdrawFromfundLessThanOrEqualTo(BigDecimal value) {
            addCriterion("withdraw_fromfund <=", value, "withdrawFromfund");
            return (Criteria) this;
        }

        public Criteria andWithdrawFromfundIn(List<BigDecimal> values) {
            addCriterion("withdraw_fromfund in", values, "withdrawFromfund");
            return (Criteria) this;
        }

        public Criteria andWithdrawFromfundNotIn(List<BigDecimal> values) {
            addCriterion("withdraw_fromfund not in", values, "withdrawFromfund");
            return (Criteria) this;
        }

        public Criteria andWithdrawFromfundBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("withdraw_fromfund between", value1, value2, "withdrawFromfund");
            return (Criteria) this;
        }

        public Criteria andWithdrawFromfundNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("withdraw_fromfund not between", value1, value2, "withdrawFromfund");
            return (Criteria) this;
        }

        public Criteria andWithdrawStateIsNull() {
            addCriterion("withdraw_state is null");
            return (Criteria) this;
        }

        public Criteria andWithdrawStateIsNotNull() {
            addCriterion("withdraw_state is not null");
            return (Criteria) this;
        }

        public Criteria andWithdrawStateEqualTo(Byte value) {
            addCriterion("withdraw_state =", value, "withdrawState");
            return (Criteria) this;
        }

        public Criteria andWithdrawStateNotEqualTo(Byte value) {
            addCriterion("withdraw_state <>", value, "withdrawState");
            return (Criteria) this;
        }

        public Criteria andWithdrawStateGreaterThan(Byte value) {
            addCriterion("withdraw_state >", value, "withdrawState");
            return (Criteria) this;
        }

        public Criteria andWithdrawStateGreaterThanOrEqualTo(Byte value) {
            addCriterion("withdraw_state >=", value, "withdrawState");
            return (Criteria) this;
        }

        public Criteria andWithdrawStateLessThan(Byte value) {
            addCriterion("withdraw_state <", value, "withdrawState");
            return (Criteria) this;
        }

        public Criteria andWithdrawStateLessThanOrEqualTo(Byte value) {
            addCriterion("withdraw_state <=", value, "withdrawState");
            return (Criteria) this;
        }

        public Criteria andWithdrawStateIn(List<Byte> values) {
            addCriterion("withdraw_state in", values, "withdrawState");
            return (Criteria) this;
        }

        public Criteria andWithdrawStateNotIn(List<Byte> values) {
            addCriterion("withdraw_state not in", values, "withdrawState");
            return (Criteria) this;
        }

        public Criteria andWithdrawStateBetween(Byte value1, Byte value2) {
            addCriterion("withdraw_state between", value1, value2, "withdrawState");
            return (Criteria) this;
        }

        public Criteria andWithdrawStateNotBetween(Byte value1, Byte value2) {
            addCriterion("withdraw_state not between", value1, value2, "withdrawState");
            return (Criteria) this;
        }

        public Criteria andWithdrawTypeIsNull() {
            addCriterion("withdraw_type is null");
            return (Criteria) this;
        }

        public Criteria andWithdrawTypeIsNotNull() {
            addCriterion("withdraw_type is not null");
            return (Criteria) this;
        }

        public Criteria andWithdrawTypeEqualTo(Byte value) {
            addCriterion("withdraw_type =", value, "withdrawType");
            return (Criteria) this;
        }

        public Criteria andWithdrawTypeNotEqualTo(Byte value) {
            addCriterion("withdraw_type <>", value, "withdrawType");
            return (Criteria) this;
        }

        public Criteria andWithdrawTypeGreaterThan(Byte value) {
            addCriterion("withdraw_type >", value, "withdrawType");
            return (Criteria) this;
        }

        public Criteria andWithdrawTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("withdraw_type >=", value, "withdrawType");
            return (Criteria) this;
        }

        public Criteria andWithdrawTypeLessThan(Byte value) {
            addCriterion("withdraw_type <", value, "withdrawType");
            return (Criteria) this;
        }

        public Criteria andWithdrawTypeLessThanOrEqualTo(Byte value) {
            addCriterion("withdraw_type <=", value, "withdrawType");
            return (Criteria) this;
        }

        public Criteria andWithdrawTypeIn(List<Byte> values) {
            addCriterion("withdraw_type in", values, "withdrawType");
            return (Criteria) this;
        }

        public Criteria andWithdrawTypeNotIn(List<Byte> values) {
            addCriterion("withdraw_type not in", values, "withdrawType");
            return (Criteria) this;
        }

        public Criteria andWithdrawTypeBetween(Byte value1, Byte value2) {
            addCriterion("withdraw_type between", value1, value2, "withdrawType");
            return (Criteria) this;
        }

        public Criteria andWithdrawTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("withdraw_type not between", value1, value2, "withdrawType");
            return (Criteria) this;
        }

        public Criteria andFailReasonIsNull() {
            addCriterion("fail_reason is null");
            return (Criteria) this;
        }

        public Criteria andFailReasonIsNotNull() {
            addCriterion("fail_reason is not null");
            return (Criteria) this;
        }

        public Criteria andFailReasonEqualTo(String value) {
            addCriterion("fail_reason =", value, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonNotEqualTo(String value) {
            addCriterion("fail_reason <>", value, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonGreaterThan(String value) {
            addCriterion("fail_reason >", value, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonGreaterThanOrEqualTo(String value) {
            addCriterion("fail_reason >=", value, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonLessThan(String value) {
            addCriterion("fail_reason <", value, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonLessThanOrEqualTo(String value) {
            addCriterion("fail_reason <=", value, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonLike(String value) {
            addCriterion("fail_reason like", value, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonNotLike(String value) {
            addCriterion("fail_reason not like", value, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonIn(List<String> values) {
            addCriterion("fail_reason in", values, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonNotIn(List<String> values) {
            addCriterion("fail_reason not in", values, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonBetween(String value1, String value2) {
            addCriterion("fail_reason between", value1, value2, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonNotBetween(String value1, String value2) {
            addCriterion("fail_reason not between", value1, value2, "failReason");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(String value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(String value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(String value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(String value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(String value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLike(String value) {
            addCriterion("order_id like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotLike(String value) {
            addCriterion("order_id not like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<String> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<String> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(String value1, String value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(String value1, String value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andIsMigratedIsNull() {
            addCriterion("is_migrated is null");
            return (Criteria) this;
        }

        public Criteria andIsMigratedIsNotNull() {
            addCriterion("is_migrated is not null");
            return (Criteria) this;
        }

        public Criteria andIsMigratedEqualTo(Boolean value) {
            addCriterion("is_migrated =", value, "isMigrated");
            return (Criteria) this;
        }

        public Criteria andIsMigratedNotEqualTo(Boolean value) {
            addCriterion("is_migrated <>", value, "isMigrated");
            return (Criteria) this;
        }

        public Criteria andIsMigratedGreaterThan(Boolean value) {
            addCriterion("is_migrated >", value, "isMigrated");
            return (Criteria) this;
        }

        public Criteria andIsMigratedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_migrated >=", value, "isMigrated");
            return (Criteria) this;
        }

        public Criteria andIsMigratedLessThan(Boolean value) {
            addCriterion("is_migrated <", value, "isMigrated");
            return (Criteria) this;
        }

        public Criteria andIsMigratedLessThanOrEqualTo(Boolean value) {
            addCriterion("is_migrated <=", value, "isMigrated");
            return (Criteria) this;
        }

        public Criteria andIsMigratedIn(List<Boolean> values) {
            addCriterion("is_migrated in", values, "isMigrated");
            return (Criteria) this;
        }

        public Criteria andIsMigratedNotIn(List<Boolean> values) {
            addCriterion("is_migrated not in", values, "isMigrated");
            return (Criteria) this;
        }

        public Criteria andIsMigratedBetween(Boolean value1, Boolean value2) {
            addCriterion("is_migrated between", value1, value2, "isMigrated");
            return (Criteria) this;
        }

        public Criteria andIsMigratedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_migrated not between", value1, value2, "isMigrated");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table trans_withdraw
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table trans_withdraw
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}