package com.weshare.thunder.model;

import java.math.BigDecimal;

public class TransWithdraw {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_withdraw.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_withdraw.gid
     *
     * @mbggenerated
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_withdraw.user_gid
     *
     * @mbggenerated
     */
    private String userGid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_withdraw.withdraw_card_gid
     *
     * @mbggenerated
     */
    private String withdrawCardGid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_withdraw.create_time
     *
     * @mbggenerated
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_withdraw.update_time
     *
     * @mbggenerated
     */
    private Integer updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_withdraw.record_withdraw_anytime_gid
     *
     * @mbggenerated
     */
    private String recordWithdrawAnytimeGid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_withdraw.withdraw_amount
     *
     * @mbggenerated
     */
    private BigDecimal withdrawAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_withdraw.withdraw_capital
     *
     * @mbggenerated
     */
    private BigDecimal withdrawCapital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_withdraw.withdraw_earning
     *
     * @mbggenerated
     */
    private BigDecimal withdrawEarning;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_withdraw.withdraw_fromnogains
     *
     * @mbggenerated
     */
    private BigDecimal withdrawFromnogains;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_withdraw.withdraw_fromfund
     *
     * @mbggenerated
     */
    private BigDecimal withdrawFromfund;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_withdraw.withdraw_state
     *
     * @mbggenerated
     */
    private Byte withdrawState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_withdraw.withdraw_type
     *
     * @mbggenerated
     */
    private Byte withdrawType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_withdraw.fail_reason
     *
     * @mbggenerated
     */
    private String failReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_withdraw.order_id
     *
     * @mbggenerated
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_withdraw.is_migrated
     *
     * @mbggenerated
     */
    private Boolean isMigrated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_withdraw.id
     *
     * @return the value of trans_withdraw.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_withdraw.id
     *
     * @param id the value for trans_withdraw.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_withdraw.gid
     *
     * @return the value of trans_withdraw.gid
     *
     * @mbggenerated
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_withdraw.gid
     *
     * @param gid the value for trans_withdraw.gid
     *
     * @mbggenerated
     */
    public void setGid(String gid) {
        this.gid = gid == null ? null : gid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_withdraw.user_gid
     *
     * @return the value of trans_withdraw.user_gid
     *
     * @mbggenerated
     */
    public String getUserGid() {
        return userGid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_withdraw.user_gid
     *
     * @param userGid the value for trans_withdraw.user_gid
     *
     * @mbggenerated
     */
    public void setUserGid(String userGid) {
        this.userGid = userGid == null ? null : userGid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_withdraw.withdraw_card_gid
     *
     * @return the value of trans_withdraw.withdraw_card_gid
     *
     * @mbggenerated
     */
    public String getWithdrawCardGid() {
        return withdrawCardGid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_withdraw.withdraw_card_gid
     *
     * @param withdrawCardGid the value for trans_withdraw.withdraw_card_gid
     *
     * @mbggenerated
     */
    public void setWithdrawCardGid(String withdrawCardGid) {
        this.withdrawCardGid = withdrawCardGid == null ? null : withdrawCardGid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_withdraw.create_time
     *
     * @return the value of trans_withdraw.create_time
     *
     * @mbggenerated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_withdraw.create_time
     *
     * @param createTime the value for trans_withdraw.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_withdraw.update_time
     *
     * @return the value of trans_withdraw.update_time
     *
     * @mbggenerated
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_withdraw.update_time
     *
     * @param updateTime the value for trans_withdraw.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_withdraw.record_withdraw_anytime_gid
     *
     * @return the value of trans_withdraw.record_withdraw_anytime_gid
     *
     * @mbggenerated
     */
    public String getRecordWithdrawAnytimeGid() {
        return recordWithdrawAnytimeGid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_withdraw.record_withdraw_anytime_gid
     *
     * @param recordWithdrawAnytimeGid the value for trans_withdraw.record_withdraw_anytime_gid
     *
     * @mbggenerated
     */
    public void setRecordWithdrawAnytimeGid(String recordWithdrawAnytimeGid) {
        this.recordWithdrawAnytimeGid = recordWithdrawAnytimeGid == null ? null : recordWithdrawAnytimeGid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_withdraw.withdraw_amount
     *
     * @return the value of trans_withdraw.withdraw_amount
     *
     * @mbggenerated
     */
    public BigDecimal getWithdrawAmount() {
        return withdrawAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_withdraw.withdraw_amount
     *
     * @param withdrawAmount the value for trans_withdraw.withdraw_amount
     *
     * @mbggenerated
     */
    public void setWithdrawAmount(BigDecimal withdrawAmount) {
        this.withdrawAmount = withdrawAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_withdraw.withdraw_capital
     *
     * @return the value of trans_withdraw.withdraw_capital
     *
     * @mbggenerated
     */
    public BigDecimal getWithdrawCapital() {
        return withdrawCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_withdraw.withdraw_capital
     *
     * @param withdrawCapital the value for trans_withdraw.withdraw_capital
     *
     * @mbggenerated
     */
    public void setWithdrawCapital(BigDecimal withdrawCapital) {
        this.withdrawCapital = withdrawCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_withdraw.withdraw_earning
     *
     * @return the value of trans_withdraw.withdraw_earning
     *
     * @mbggenerated
     */
    public BigDecimal getWithdrawEarning() {
        return withdrawEarning;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_withdraw.withdraw_earning
     *
     * @param withdrawEarning the value for trans_withdraw.withdraw_earning
     *
     * @mbggenerated
     */
    public void setWithdrawEarning(BigDecimal withdrawEarning) {
        this.withdrawEarning = withdrawEarning;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_withdraw.withdraw_fromnogains
     *
     * @return the value of trans_withdraw.withdraw_fromnogains
     *
     * @mbggenerated
     */
    public BigDecimal getWithdrawFromnogains() {
        return withdrawFromnogains;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_withdraw.withdraw_fromnogains
     *
     * @param withdrawFromnogains the value for trans_withdraw.withdraw_fromnogains
     *
     * @mbggenerated
     */
    public void setWithdrawFromnogains(BigDecimal withdrawFromnogains) {
        this.withdrawFromnogains = withdrawFromnogains;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_withdraw.withdraw_fromfund
     *
     * @return the value of trans_withdraw.withdraw_fromfund
     *
     * @mbggenerated
     */
    public BigDecimal getWithdrawFromfund() {
        return withdrawFromfund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_withdraw.withdraw_fromfund
     *
     * @param withdrawFromfund the value for trans_withdraw.withdraw_fromfund
     *
     * @mbggenerated
     */
    public void setWithdrawFromfund(BigDecimal withdrawFromfund) {
        this.withdrawFromfund = withdrawFromfund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_withdraw.withdraw_state
     *
     * @return the value of trans_withdraw.withdraw_state
     *
     * @mbggenerated
     */
    public Byte getWithdrawState() {
        return withdrawState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_withdraw.withdraw_state
     *
     * @param withdrawState the value for trans_withdraw.withdraw_state
     *
     * @mbggenerated
     */
    public void setWithdrawState(Byte withdrawState) {
        this.withdrawState = withdrawState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_withdraw.withdraw_type
     *
     * @return the value of trans_withdraw.withdraw_type
     *
     * @mbggenerated
     */
    public Byte getWithdrawType() {
        return withdrawType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_withdraw.withdraw_type
     *
     * @param withdrawType the value for trans_withdraw.withdraw_type
     *
     * @mbggenerated
     */
    public void setWithdrawType(Byte withdrawType) {
        this.withdrawType = withdrawType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_withdraw.fail_reason
     *
     * @return the value of trans_withdraw.fail_reason
     *
     * @mbggenerated
     */
    public String getFailReason() {
        return failReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_withdraw.fail_reason
     *
     * @param failReason the value for trans_withdraw.fail_reason
     *
     * @mbggenerated
     */
    public void setFailReason(String failReason) {
        this.failReason = failReason == null ? null : failReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_withdraw.order_id
     *
     * @return the value of trans_withdraw.order_id
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_withdraw.order_id
     *
     * @param orderId the value for trans_withdraw.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_withdraw.is_migrated
     *
     * @return the value of trans_withdraw.is_migrated
     *
     * @mbggenerated
     */
    public Boolean getIsMigrated() {
        return isMigrated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_withdraw.is_migrated
     *
     * @param isMigrated the value for trans_withdraw.is_migrated
     *
     * @mbggenerated
     */
    public void setIsMigrated(Boolean isMigrated) {
        this.isMigrated = isMigrated;
    }

    //Customer Definition
    public static final byte STATE_ONGOING = 0;
    public static final byte STATE_SUCCESS = 1;
    public static final byte STATE_FAIL = 2;

    public static final byte TYPE_LOAN = 0;
    public static final byte TYPE_DEPOSIT = 1;

    public void clear() {
        id = null;
        gid = null;
        userGid = null;
        withdrawCardGid = null;
        createTime = null;
        updateTime = null;
        withdrawAmount = null;
        withdrawCapital = null;
        withdrawEarning = null;
        withdrawFromnogains = null;
        withdrawFromfund = null;
        withdrawState = null;
        withdrawType = null;
        failReason = null;
        orderId = null;
        isMigrated = null;
    }

}