package com.weshare.thunder.model;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.date
     *
     * @mbggenerated
     */
    private Integer date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.total
     *
     * @mbggenerated
     */
    private Integer total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.not_activited
     *
     * @mbggenerated
     */
    private Integer notActivited;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.activited
     *
     * @mbggenerated
     */
    private Integer activited;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.bind_mobile
     *
     * @mbggenerated
     */
    private Integer bindMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.certified
     *
     * @mbggenerated
     */
    private Integer certified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.bind_card
     *
     * @mbggenerated
     */
    private Integer bindCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.deposited
     *
     * @mbggenerated
     */
    private Integer deposited;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.not_follow_total
     *
     * @mbggenerated
     */
    private Integer notFollowTotal;

    private Integer totalFinancePeoples;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @param id the value for user_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.date
     *
     * @return the value of user_info.date
     *
     * @mbggenerated
     */
    public Integer getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.date
     *
     * @param date the value for user_info.date
     *
     * @mbggenerated
     */
    public void setDate(Integer date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.total
     *
     * @return the value of user_info.total
     *
     * @mbggenerated
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.total
     *
     * @param total the value for user_info.total
     *
     * @mbggenerated
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.not_activited
     *
     * @return the value of user_info.not_activited
     *
     * @mbggenerated
     */
    public Integer getNotActivited() {
        return notActivited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.not_activited
     *
     * @param notActivited the value for user_info.not_activited
     *
     * @mbggenerated
     */
    public void setNotActivited(Integer notActivited) {
        this.notActivited = notActivited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.activited
     *
     * @return the value of user_info.activited
     *
     * @mbggenerated
     */
    public Integer getActivited() {
        return activited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.activited
     *
     * @param activited the value for user_info.activited
     *
     * @mbggenerated
     */
    public void setActivited(Integer activited) {
        this.activited = activited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.bind_mobile
     *
     * @return the value of user_info.bind_mobile
     *
     * @mbggenerated
     */
    public Integer getBindMobile() {
        return bindMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.bind_mobile
     *
     * @param bindMobile the value for user_info.bind_mobile
     *
     * @mbggenerated
     */
    public void setBindMobile(Integer bindMobile) {
        this.bindMobile = bindMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.certified
     *
     * @return the value of user_info.certified
     *
     * @mbggenerated
     */
    public Integer getCertified() {
        return certified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.certified
     *
     * @param certified the value for user_info.certified
     *
     * @mbggenerated
     */
    public void setCertified(Integer certified) {
        this.certified = certified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.bind_card
     *
     * @return the value of user_info.bind_card
     *
     * @mbggenerated
     */
    public Integer getBindCard() {
        return bindCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.bind_card
     *
     * @param bindCard the value for user_info.bind_card
     *
     * @mbggenerated
     */
    public void setBindCard(Integer bindCard) {
        this.bindCard = bindCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.deposited
     *
     * @return the value of user_info.deposited
     *
     * @mbggenerated
     */
    public Integer getDeposited() {
        return deposited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.deposited
     *
     * @param deposited the value for user_info.deposited
     *
     * @mbggenerated
     */
    public void setDeposited(Integer deposited) {
        this.deposited = deposited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.not_follow_total
     *
     * @return the value of user_info.not_follow_total
     *
     * @mbggenerated
     */
    public Integer getNotFollowTotal() {
        return notFollowTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.not_follow_total
     *
     * @param notFollowTotal the value for user_info.not_follow_total
     *
     * @mbggenerated
     */
    public void setNotFollowTotal(Integer notFollowTotal) {
        this.notFollowTotal = notFollowTotal;
    }

    public Integer getTotalFinancePeoples() {
        return totalFinancePeoples;
    }

    public void setTotalFinancePeoples(Integer totalFinancePeoples) {
        this.totalFinancePeoples = totalFinancePeoples;
    }
}