package com.weshare.thunder.model;

import java.util.ArrayList;
import java.util.List;

public class UserLightningExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_lightning
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_lightning
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_lightning
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_lightning
     *
     * @mbggenerated
     */
    public UserLightningExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_lightning
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_lightning
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_lightning
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_lightning
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_lightning
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_lightning
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_lightning
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_lightning
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_lightning
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_lightning
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_lightning
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserGidIsNull() {
            addCriterion("user_gid is null");
            return (Criteria) this;
        }

        public Criteria andUserGidIsNotNull() {
            addCriterion("user_gid is not null");
            return (Criteria) this;
        }

        public Criteria andUserGidEqualTo(String value) {
            addCriterion("user_gid =", value, "userGid");
            return (Criteria) this;
        }

        public Criteria andUserGidNotEqualTo(String value) {
            addCriterion("user_gid <>", value, "userGid");
            return (Criteria) this;
        }

        public Criteria andUserGidGreaterThan(String value) {
            addCriterion("user_gid >", value, "userGid");
            return (Criteria) this;
        }

        public Criteria andUserGidGreaterThanOrEqualTo(String value) {
            addCriterion("user_gid >=", value, "userGid");
            return (Criteria) this;
        }

        public Criteria andUserGidLessThan(String value) {
            addCriterion("user_gid <", value, "userGid");
            return (Criteria) this;
        }

        public Criteria andUserGidLessThanOrEqualTo(String value) {
            addCriterion("user_gid <=", value, "userGid");
            return (Criteria) this;
        }

        public Criteria andUserGidLike(String value) {
            addCriterion("user_gid like", value, "userGid");
            return (Criteria) this;
        }

        public Criteria andUserGidNotLike(String value) {
            addCriterion("user_gid not like", value, "userGid");
            return (Criteria) this;
        }

        public Criteria andUserGidIn(List<String> values) {
            addCriterion("user_gid in", values, "userGid");
            return (Criteria) this;
        }

        public Criteria andUserGidNotIn(List<String> values) {
            addCriterion("user_gid not in", values, "userGid");
            return (Criteria) this;
        }

        public Criteria andUserGidBetween(String value1, String value2) {
            addCriterion("user_gid between", value1, value2, "userGid");
            return (Criteria) this;
        }

        public Criteria andUserGidNotBetween(String value1, String value2) {
            addCriterion("user_gid not between", value1, value2, "userGid");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Integer value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Integer value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Integer value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Integer value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Integer value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Integer> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Integer> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Integer value1, Integer value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Integer value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Integer value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Integer value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Integer value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Integer value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Integer> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Integer> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Integer value1, Integer value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andInvitationCodeIsNull() {
            addCriterion("invitation_code is null");
            return (Criteria) this;
        }

        public Criteria andInvitationCodeIsNotNull() {
            addCriterion("invitation_code is not null");
            return (Criteria) this;
        }

        public Criteria andInvitationCodeEqualTo(String value) {
            addCriterion("invitation_code =", value, "invitationCode");
            return (Criteria) this;
        }

        public Criteria andInvitationCodeNotEqualTo(String value) {
            addCriterion("invitation_code <>", value, "invitationCode");
            return (Criteria) this;
        }

        public Criteria andInvitationCodeGreaterThan(String value) {
            addCriterion("invitation_code >", value, "invitationCode");
            return (Criteria) this;
        }

        public Criteria andInvitationCodeGreaterThanOrEqualTo(String value) {
            addCriterion("invitation_code >=", value, "invitationCode");
            return (Criteria) this;
        }

        public Criteria andInvitationCodeLessThan(String value) {
            addCriterion("invitation_code <", value, "invitationCode");
            return (Criteria) this;
        }

        public Criteria andInvitationCodeLessThanOrEqualTo(String value) {
            addCriterion("invitation_code <=", value, "invitationCode");
            return (Criteria) this;
        }

        public Criteria andInvitationCodeLike(String value) {
            addCriterion("invitation_code like", value, "invitationCode");
            return (Criteria) this;
        }

        public Criteria andInvitationCodeNotLike(String value) {
            addCriterion("invitation_code not like", value, "invitationCode");
            return (Criteria) this;
        }

        public Criteria andInvitationCodeIn(List<String> values) {
            addCriterion("invitation_code in", values, "invitationCode");
            return (Criteria) this;
        }

        public Criteria andInvitationCodeNotIn(List<String> values) {
            addCriterion("invitation_code not in", values, "invitationCode");
            return (Criteria) this;
        }

        public Criteria andInvitationCodeBetween(String value1, String value2) {
            addCriterion("invitation_code between", value1, value2, "invitationCode");
            return (Criteria) this;
        }

        public Criteria andInvitationCodeNotBetween(String value1, String value2) {
            addCriterion("invitation_code not between", value1, value2, "invitationCode");
            return (Criteria) this;
        }

        public Criteria andSceneIdIsNull() {
            addCriterion("scene_id is null");
            return (Criteria) this;
        }

        public Criteria andSceneIdIsNotNull() {
            addCriterion("scene_id is not null");
            return (Criteria) this;
        }

        public Criteria andSceneIdEqualTo(Integer value) {
            addCriterion("scene_id =", value, "sceneId");
            return (Criteria) this;
        }

        public Criteria andSceneIdNotEqualTo(Integer value) {
            addCriterion("scene_id <>", value, "sceneId");
            return (Criteria) this;
        }

        public Criteria andSceneIdGreaterThan(Integer value) {
            addCriterion("scene_id >", value, "sceneId");
            return (Criteria) this;
        }

        public Criteria andSceneIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("scene_id >=", value, "sceneId");
            return (Criteria) this;
        }

        public Criteria andSceneIdLessThan(Integer value) {
            addCriterion("scene_id <", value, "sceneId");
            return (Criteria) this;
        }

        public Criteria andSceneIdLessThanOrEqualTo(Integer value) {
            addCriterion("scene_id <=", value, "sceneId");
            return (Criteria) this;
        }

        public Criteria andSceneIdIn(List<Integer> values) {
            addCriterion("scene_id in", values, "sceneId");
            return (Criteria) this;
        }

        public Criteria andSceneIdNotIn(List<Integer> values) {
            addCriterion("scene_id not in", values, "sceneId");
            return (Criteria) this;
        }

        public Criteria andSceneIdBetween(Integer value1, Integer value2) {
            addCriterion("scene_id between", value1, value2, "sceneId");
            return (Criteria) this;
        }

        public Criteria andSceneIdNotBetween(Integer value1, Integer value2) {
            addCriterion("scene_id not between", value1, value2, "sceneId");
            return (Criteria) this;
        }

        public Criteria andTicketIsNull() {
            addCriterion("ticket is null");
            return (Criteria) this;
        }

        public Criteria andTicketIsNotNull() {
            addCriterion("ticket is not null");
            return (Criteria) this;
        }

        public Criteria andTicketEqualTo(String value) {
            addCriterion("ticket =", value, "ticket");
            return (Criteria) this;
        }

        public Criteria andTicketNotEqualTo(String value) {
            addCriterion("ticket <>", value, "ticket");
            return (Criteria) this;
        }

        public Criteria andTicketGreaterThan(String value) {
            addCriterion("ticket >", value, "ticket");
            return (Criteria) this;
        }

        public Criteria andTicketGreaterThanOrEqualTo(String value) {
            addCriterion("ticket >=", value, "ticket");
            return (Criteria) this;
        }

        public Criteria andTicketLessThan(String value) {
            addCriterion("ticket <", value, "ticket");
            return (Criteria) this;
        }

        public Criteria andTicketLessThanOrEqualTo(String value) {
            addCriterion("ticket <=", value, "ticket");
            return (Criteria) this;
        }

        public Criteria andTicketLike(String value) {
            addCriterion("ticket like", value, "ticket");
            return (Criteria) this;
        }

        public Criteria andTicketNotLike(String value) {
            addCriterion("ticket not like", value, "ticket");
            return (Criteria) this;
        }

        public Criteria andTicketIn(List<String> values) {
            addCriterion("ticket in", values, "ticket");
            return (Criteria) this;
        }

        public Criteria andTicketNotIn(List<String> values) {
            addCriterion("ticket not in", values, "ticket");
            return (Criteria) this;
        }

        public Criteria andTicketBetween(String value1, String value2) {
            addCriterion("ticket between", value1, value2, "ticket");
            return (Criteria) this;
        }

        public Criteria andTicketNotBetween(String value1, String value2) {
            addCriterion("ticket not between", value1, value2, "ticket");
            return (Criteria) this;
        }

        public Criteria andInviterGidIsNull() {
            addCriterion("inviter_gid is null");
            return (Criteria) this;
        }

        public Criteria andInviterGidIsNotNull() {
            addCriterion("inviter_gid is not null");
            return (Criteria) this;
        }

        public Criteria andInviterGidEqualTo(String value) {
            addCriterion("inviter_gid =", value, "inviterGid");
            return (Criteria) this;
        }

        public Criteria andInviterGidNotEqualTo(String value) {
            addCriterion("inviter_gid <>", value, "inviterGid");
            return (Criteria) this;
        }

        public Criteria andInviterGidGreaterThan(String value) {
            addCriterion("inviter_gid >", value, "inviterGid");
            return (Criteria) this;
        }

        public Criteria andInviterGidGreaterThanOrEqualTo(String value) {
            addCriterion("inviter_gid >=", value, "inviterGid");
            return (Criteria) this;
        }

        public Criteria andInviterGidLessThan(String value) {
            addCriterion("inviter_gid <", value, "inviterGid");
            return (Criteria) this;
        }

        public Criteria andInviterGidLessThanOrEqualTo(String value) {
            addCriterion("inviter_gid <=", value, "inviterGid");
            return (Criteria) this;
        }

        public Criteria andInviterGidLike(String value) {
            addCriterion("inviter_gid like", value, "inviterGid");
            return (Criteria) this;
        }

        public Criteria andInviterGidNotLike(String value) {
            addCriterion("inviter_gid not like", value, "inviterGid");
            return (Criteria) this;
        }

        public Criteria andInviterGidIn(List<String> values) {
            addCriterion("inviter_gid in", values, "inviterGid");
            return (Criteria) this;
        }

        public Criteria andInviterGidNotIn(List<String> values) {
            addCriterion("inviter_gid not in", values, "inviterGid");
            return (Criteria) this;
        }

        public Criteria andInviterGidBetween(String value1, String value2) {
            addCriterion("inviter_gid between", value1, value2, "inviterGid");
            return (Criteria) this;
        }

        public Criteria andInviterGidNotBetween(String value1, String value2) {
            addCriterion("inviter_gid not between", value1, value2, "inviterGid");
            return (Criteria) this;
        }

        public Criteria andInvitedCountIsNull() {
            addCriterion("invited_count is null");
            return (Criteria) this;
        }

        public Criteria andInvitedCountIsNotNull() {
            addCriterion("invited_count is not null");
            return (Criteria) this;
        }

        public Criteria andInvitedCountEqualTo(Integer value) {
            addCriterion("invited_count =", value, "invitedCount");
            return (Criteria) this;
        }

        public Criteria andInvitedCountNotEqualTo(Integer value) {
            addCriterion("invited_count <>", value, "invitedCount");
            return (Criteria) this;
        }

        public Criteria andInvitedCountGreaterThan(Integer value) {
            addCriterion("invited_count >", value, "invitedCount");
            return (Criteria) this;
        }

        public Criteria andInvitedCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("invited_count >=", value, "invitedCount");
            return (Criteria) this;
        }

        public Criteria andInvitedCountLessThan(Integer value) {
            addCriterion("invited_count <", value, "invitedCount");
            return (Criteria) this;
        }

        public Criteria andInvitedCountLessThanOrEqualTo(Integer value) {
            addCriterion("invited_count <=", value, "invitedCount");
            return (Criteria) this;
        }

        public Criteria andInvitedCountIn(List<Integer> values) {
            addCriterion("invited_count in", values, "invitedCount");
            return (Criteria) this;
        }

        public Criteria andInvitedCountNotIn(List<Integer> values) {
            addCriterion("invited_count not in", values, "invitedCount");
            return (Criteria) this;
        }

        public Criteria andInvitedCountBetween(Integer value1, Integer value2) {
            addCriterion("invited_count between", value1, value2, "invitedCount");
            return (Criteria) this;
        }

        public Criteria andInvitedCountNotBetween(Integer value1, Integer value2) {
            addCriterion("invited_count not between", value1, value2, "invitedCount");
            return (Criteria) this;
        }

        public Criteria andInvitedLeftCountIsNull() {
            addCriterion("invited_left_count is null");
            return (Criteria) this;
        }

        public Criteria andInvitedLeftCountIsNotNull() {
            addCriterion("invited_left_count is not null");
            return (Criteria) this;
        }

        public Criteria andInvitedLeftCountEqualTo(Integer value) {
            addCriterion("invited_left_count =", value, "invitedLeftCount");
            return (Criteria) this;
        }

        public Criteria andInvitedLeftCountNotEqualTo(Integer value) {
            addCriterion("invited_left_count <>", value, "invitedLeftCount");
            return (Criteria) this;
        }

        public Criteria andInvitedLeftCountGreaterThan(Integer value) {
            addCriterion("invited_left_count >", value, "invitedLeftCount");
            return (Criteria) this;
        }

        public Criteria andInvitedLeftCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("invited_left_count >=", value, "invitedLeftCount");
            return (Criteria) this;
        }

        public Criteria andInvitedLeftCountLessThan(Integer value) {
            addCriterion("invited_left_count <", value, "invitedLeftCount");
            return (Criteria) this;
        }

        public Criteria andInvitedLeftCountLessThanOrEqualTo(Integer value) {
            addCriterion("invited_left_count <=", value, "invitedLeftCount");
            return (Criteria) this;
        }

        public Criteria andInvitedLeftCountIn(List<Integer> values) {
            addCriterion("invited_left_count in", values, "invitedLeftCount");
            return (Criteria) this;
        }

        public Criteria andInvitedLeftCountNotIn(List<Integer> values) {
            addCriterion("invited_left_count not in", values, "invitedLeftCount");
            return (Criteria) this;
        }

        public Criteria andInvitedLeftCountBetween(Integer value1, Integer value2) {
            addCriterion("invited_left_count between", value1, value2, "invitedLeftCount");
            return (Criteria) this;
        }

        public Criteria andInvitedLeftCountNotBetween(Integer value1, Integer value2) {
            addCriterion("invited_left_count not between", value1, value2, "invitedLeftCount");
            return (Criteria) this;
        }

        public Criteria andIsActivitedIsNull() {
            addCriterion("is_activited is null");
            return (Criteria) this;
        }

        public Criteria andIsActivitedIsNotNull() {
            addCriterion("is_activited is not null");
            return (Criteria) this;
        }

        public Criteria andIsActivitedEqualTo(Boolean value) {
            addCriterion("is_activited =", value, "isActivited");
            return (Criteria) this;
        }

        public Criteria andIsActivitedNotEqualTo(Boolean value) {
            addCriterion("is_activited <>", value, "isActivited");
            return (Criteria) this;
        }

        public Criteria andIsActivitedGreaterThan(Boolean value) {
            addCriterion("is_activited >", value, "isActivited");
            return (Criteria) this;
        }

        public Criteria andIsActivitedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_activited >=", value, "isActivited");
            return (Criteria) this;
        }

        public Criteria andIsActivitedLessThan(Boolean value) {
            addCriterion("is_activited <", value, "isActivited");
            return (Criteria) this;
        }

        public Criteria andIsActivitedLessThanOrEqualTo(Boolean value) {
            addCriterion("is_activited <=", value, "isActivited");
            return (Criteria) this;
        }

        public Criteria andIsActivitedIn(List<Boolean> values) {
            addCriterion("is_activited in", values, "isActivited");
            return (Criteria) this;
        }

        public Criteria andIsActivitedNotIn(List<Boolean> values) {
            addCriterion("is_activited not in", values, "isActivited");
            return (Criteria) this;
        }

        public Criteria andIsActivitedBetween(Boolean value1, Boolean value2) {
            addCriterion("is_activited between", value1, value2, "isActivited");
            return (Criteria) this;
        }

        public Criteria andIsActivitedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_activited not between", value1, value2, "isActivited");
            return (Criteria) this;
        }

        public Criteria andIsCertifiedIsNull() {
            addCriterion("is_certified is null");
            return (Criteria) this;
        }

        public Criteria andIsCertifiedIsNotNull() {
            addCriterion("is_certified is not null");
            return (Criteria) this;
        }

        public Criteria andIsCertifiedEqualTo(Boolean value) {
            addCriterion("is_certified =", value, "isCertified");
            return (Criteria) this;
        }

        public Criteria andIsCertifiedNotEqualTo(Boolean value) {
            addCriterion("is_certified <>", value, "isCertified");
            return (Criteria) this;
        }

        public Criteria andIsCertifiedGreaterThan(Boolean value) {
            addCriterion("is_certified >", value, "isCertified");
            return (Criteria) this;
        }

        public Criteria andIsCertifiedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_certified >=", value, "isCertified");
            return (Criteria) this;
        }

        public Criteria andIsCertifiedLessThan(Boolean value) {
            addCriterion("is_certified <", value, "isCertified");
            return (Criteria) this;
        }

        public Criteria andIsCertifiedLessThanOrEqualTo(Boolean value) {
            addCriterion("is_certified <=", value, "isCertified");
            return (Criteria) this;
        }

        public Criteria andIsCertifiedIn(List<Boolean> values) {
            addCriterion("is_certified in", values, "isCertified");
            return (Criteria) this;
        }

        public Criteria andIsCertifiedNotIn(List<Boolean> values) {
            addCriterion("is_certified not in", values, "isCertified");
            return (Criteria) this;
        }

        public Criteria andIsCertifiedBetween(Boolean value1, Boolean value2) {
            addCriterion("is_certified between", value1, value2, "isCertified");
            return (Criteria) this;
        }

        public Criteria andIsCertifiedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_certified not between", value1, value2, "isCertified");
            return (Criteria) this;
        }

        public Criteria andFirstChannelFromIsNull() {
            addCriterion("first_channel_from is null");
            return (Criteria) this;
        }

        public Criteria andFirstChannelFromIsNotNull() {
            addCriterion("first_channel_from is not null");
            return (Criteria) this;
        }

        public Criteria andFirstChannelFromEqualTo(String value) {
            addCriterion("first_channel_from =", value, "firstChannelFrom");
            return (Criteria) this;
        }

        public Criteria andFirstChannelFromNotEqualTo(String value) {
            addCriterion("first_channel_from <>", value, "firstChannelFrom");
            return (Criteria) this;
        }

        public Criteria andFirstChannelFromGreaterThan(String value) {
            addCriterion("first_channel_from >", value, "firstChannelFrom");
            return (Criteria) this;
        }

        public Criteria andFirstChannelFromGreaterThanOrEqualTo(String value) {
            addCriterion("first_channel_from >=", value, "firstChannelFrom");
            return (Criteria) this;
        }

        public Criteria andFirstChannelFromLessThan(String value) {
            addCriterion("first_channel_from <", value, "firstChannelFrom");
            return (Criteria) this;
        }

        public Criteria andFirstChannelFromLessThanOrEqualTo(String value) {
            addCriterion("first_channel_from <=", value, "firstChannelFrom");
            return (Criteria) this;
        }

        public Criteria andFirstChannelFromLike(String value) {
            addCriterion("first_channel_from like", value, "firstChannelFrom");
            return (Criteria) this;
        }

        public Criteria andFirstChannelFromNotLike(String value) {
            addCriterion("first_channel_from not like", value, "firstChannelFrom");
            return (Criteria) this;
        }

        public Criteria andFirstChannelFromIn(List<String> values) {
            addCriterion("first_channel_from in", values, "firstChannelFrom");
            return (Criteria) this;
        }

        public Criteria andFirstChannelFromNotIn(List<String> values) {
            addCriterion("first_channel_from not in", values, "firstChannelFrom");
            return (Criteria) this;
        }

        public Criteria andFirstChannelFromBetween(String value1, String value2) {
            addCriterion("first_channel_from between", value1, value2, "firstChannelFrom");
            return (Criteria) this;
        }

        public Criteria andFirstChannelFromNotBetween(String value1, String value2) {
            addCriterion("first_channel_from not between", value1, value2, "firstChannelFrom");
            return (Criteria) this;
        }

        public Criteria andFirstTryTimeIsNull() {
            addCriterion("first_try_time is null");
            return (Criteria) this;
        }

        public Criteria andFirstTryTimeIsNotNull() {
            addCriterion("first_try_time is not null");
            return (Criteria) this;
        }

        public Criteria andFirstTryTimeEqualTo(Integer value) {
            addCriterion("first_try_time =", value, "firstTryTime");
            return (Criteria) this;
        }

        public Criteria andFirstTryTimeNotEqualTo(Integer value) {
            addCriterion("first_try_time <>", value, "firstTryTime");
            return (Criteria) this;
        }

        public Criteria andFirstTryTimeGreaterThan(Integer value) {
            addCriterion("first_try_time >", value, "firstTryTime");
            return (Criteria) this;
        }

        public Criteria andFirstTryTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("first_try_time >=", value, "firstTryTime");
            return (Criteria) this;
        }

        public Criteria andFirstTryTimeLessThan(Integer value) {
            addCriterion("first_try_time <", value, "firstTryTime");
            return (Criteria) this;
        }

        public Criteria andFirstTryTimeLessThanOrEqualTo(Integer value) {
            addCriterion("first_try_time <=", value, "firstTryTime");
            return (Criteria) this;
        }

        public Criteria andFirstTryTimeIn(List<Integer> values) {
            addCriterion("first_try_time in", values, "firstTryTime");
            return (Criteria) this;
        }

        public Criteria andFirstTryTimeNotIn(List<Integer> values) {
            addCriterion("first_try_time not in", values, "firstTryTime");
            return (Criteria) this;
        }

        public Criteria andFirstTryTimeBetween(Integer value1, Integer value2) {
            addCriterion("first_try_time between", value1, value2, "firstTryTime");
            return (Criteria) this;
        }

        public Criteria andFirstTryTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("first_try_time not between", value1, value2, "firstTryTime");
            return (Criteria) this;
        }

        public Criteria andIsAutoDepositIsNull() {
            addCriterion("is_auto_deposit is null");
            return (Criteria) this;
        }

        public Criteria andIsAutoDepositIsNotNull() {
            addCriterion("is_auto_deposit is not null");
            return (Criteria) this;
        }

        public Criteria andIsAutoDepositEqualTo(Boolean value) {
            addCriterion("is_auto_deposit =", value, "isAutoDeposit");
            return (Criteria) this;
        }

        public Criteria andIsAutoDepositNotEqualTo(Boolean value) {
            addCriterion("is_auto_deposit <>", value, "isAutoDeposit");
            return (Criteria) this;
        }

        public Criteria andIsAutoDepositGreaterThan(Boolean value) {
            addCriterion("is_auto_deposit >", value, "isAutoDeposit");
            return (Criteria) this;
        }

        public Criteria andIsAutoDepositGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_auto_deposit >=", value, "isAutoDeposit");
            return (Criteria) this;
        }

        public Criteria andIsAutoDepositLessThan(Boolean value) {
            addCriterion("is_auto_deposit <", value, "isAutoDeposit");
            return (Criteria) this;
        }

        public Criteria andIsAutoDepositLessThanOrEqualTo(Boolean value) {
            addCriterion("is_auto_deposit <=", value, "isAutoDeposit");
            return (Criteria) this;
        }

        public Criteria andIsAutoDepositIn(List<Boolean> values) {
            addCriterion("is_auto_deposit in", values, "isAutoDeposit");
            return (Criteria) this;
        }

        public Criteria andIsAutoDepositNotIn(List<Boolean> values) {
            addCriterion("is_auto_deposit not in", values, "isAutoDeposit");
            return (Criteria) this;
        }

        public Criteria andIsAutoDepositBetween(Boolean value1, Boolean value2) {
            addCriterion("is_auto_deposit between", value1, value2, "isAutoDeposit");
            return (Criteria) this;
        }

        public Criteria andIsAutoDepositNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_auto_deposit not between", value1, value2, "isAutoDeposit");
            return (Criteria) this;
        }

        public Criteria andIsDepositIsNull() {
            addCriterion("is_deposit is null");
            return (Criteria) this;
        }

        public Criteria andIsDepositIsNotNull() {
            addCriterion("is_deposit is not null");
            return (Criteria) this;
        }

        public Criteria andIsDepositEqualTo(Boolean value) {
            addCriterion("is_deposit =", value, "isDeposit");
            return (Criteria) this;
        }

        public Criteria andIsDepositNotEqualTo(Boolean value) {
            addCriterion("is_deposit <>", value, "isDeposit");
            return (Criteria) this;
        }

        public Criteria andIsDepositGreaterThan(Boolean value) {
            addCriterion("is_deposit >", value, "isDeposit");
            return (Criteria) this;
        }

        public Criteria andIsDepositGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_deposit >=", value, "isDeposit");
            return (Criteria) this;
        }

        public Criteria andIsDepositLessThan(Boolean value) {
            addCriterion("is_deposit <", value, "isDeposit");
            return (Criteria) this;
        }

        public Criteria andIsDepositLessThanOrEqualTo(Boolean value) {
            addCriterion("is_deposit <=", value, "isDeposit");
            return (Criteria) this;
        }

        public Criteria andIsDepositIn(List<Boolean> values) {
            addCriterion("is_deposit in", values, "isDeposit");
            return (Criteria) this;
        }

        public Criteria andIsDepositNotIn(List<Boolean> values) {
            addCriterion("is_deposit not in", values, "isDeposit");
            return (Criteria) this;
        }

        public Criteria andIsDepositBetween(Boolean value1, Boolean value2) {
            addCriterion("is_deposit between", value1, value2, "isDeposit");
            return (Criteria) this;
        }

        public Criteria andIsDepositNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_deposit not between", value1, value2, "isDeposit");
            return (Criteria) this;
        }

        public Criteria andIsLoanIsNull() {
            addCriterion("is_loan is null");
            return (Criteria) this;
        }

        public Criteria andIsLoanIsNotNull() {
            addCriterion("is_loan is not null");
            return (Criteria) this;
        }

        public Criteria andIsLoanEqualTo(Boolean value) {
            addCriterion("is_loan =", value, "isLoan");
            return (Criteria) this;
        }

        public Criteria andIsLoanNotEqualTo(Boolean value) {
            addCriterion("is_loan <>", value, "isLoan");
            return (Criteria) this;
        }

        public Criteria andIsLoanGreaterThan(Boolean value) {
            addCriterion("is_loan >", value, "isLoan");
            return (Criteria) this;
        }

        public Criteria andIsLoanGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_loan >=", value, "isLoan");
            return (Criteria) this;
        }

        public Criteria andIsLoanLessThan(Boolean value) {
            addCriterion("is_loan <", value, "isLoan");
            return (Criteria) this;
        }

        public Criteria andIsLoanLessThanOrEqualTo(Boolean value) {
            addCriterion("is_loan <=", value, "isLoan");
            return (Criteria) this;
        }

        public Criteria andIsLoanIn(List<Boolean> values) {
            addCriterion("is_loan in", values, "isLoan");
            return (Criteria) this;
        }

        public Criteria andIsLoanNotIn(List<Boolean> values) {
            addCriterion("is_loan not in", values, "isLoan");
            return (Criteria) this;
        }

        public Criteria andIsLoanBetween(Boolean value1, Boolean value2) {
            addCriterion("is_loan between", value1, value2, "isLoan");
            return (Criteria) this;
        }

        public Criteria andIsLoanNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_loan not between", value1, value2, "isLoan");
            return (Criteria) this;
        }

        public Criteria andDepositIsSignedIsNull() {
            addCriterion("deposit_is_signed is null");
            return (Criteria) this;
        }

        public Criteria andDepositIsSignedIsNotNull() {
            addCriterion("deposit_is_signed is not null");
            return (Criteria) this;
        }

        public Criteria andDepositIsSignedEqualTo(Boolean value) {
            addCriterion("deposit_is_signed =", value, "depositIsSigned");
            return (Criteria) this;
        }

        public Criteria andDepositIsSignedNotEqualTo(Boolean value) {
            addCriterion("deposit_is_signed <>", value, "depositIsSigned");
            return (Criteria) this;
        }

        public Criteria andDepositIsSignedGreaterThan(Boolean value) {
            addCriterion("deposit_is_signed >", value, "depositIsSigned");
            return (Criteria) this;
        }

        public Criteria andDepositIsSignedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("deposit_is_signed >=", value, "depositIsSigned");
            return (Criteria) this;
        }

        public Criteria andDepositIsSignedLessThan(Boolean value) {
            addCriterion("deposit_is_signed <", value, "depositIsSigned");
            return (Criteria) this;
        }

        public Criteria andDepositIsSignedLessThanOrEqualTo(Boolean value) {
            addCriterion("deposit_is_signed <=", value, "depositIsSigned");
            return (Criteria) this;
        }

        public Criteria andDepositIsSignedIn(List<Boolean> values) {
            addCriterion("deposit_is_signed in", values, "depositIsSigned");
            return (Criteria) this;
        }

        public Criteria andDepositIsSignedNotIn(List<Boolean> values) {
            addCriterion("deposit_is_signed not in", values, "depositIsSigned");
            return (Criteria) this;
        }

        public Criteria andDepositIsSignedBetween(Boolean value1, Boolean value2) {
            addCriterion("deposit_is_signed between", value1, value2, "depositIsSigned");
            return (Criteria) this;
        }

        public Criteria andDepositIsSignedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("deposit_is_signed not between", value1, value2, "depositIsSigned");
            return (Criteria) this;
        }

        public Criteria andLoanIsSignedIsNull() {
            addCriterion("loan_is_signed is null");
            return (Criteria) this;
        }

        public Criteria andLoanIsSignedIsNotNull() {
            addCriterion("loan_is_signed is not null");
            return (Criteria) this;
        }

        public Criteria andLoanIsSignedEqualTo(Boolean value) {
            addCriterion("loan_is_signed =", value, "loanIsSigned");
            return (Criteria) this;
        }

        public Criteria andLoanIsSignedNotEqualTo(Boolean value) {
            addCriterion("loan_is_signed <>", value, "loanIsSigned");
            return (Criteria) this;
        }

        public Criteria andLoanIsSignedGreaterThan(Boolean value) {
            addCriterion("loan_is_signed >", value, "loanIsSigned");
            return (Criteria) this;
        }

        public Criteria andLoanIsSignedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("loan_is_signed >=", value, "loanIsSigned");
            return (Criteria) this;
        }

        public Criteria andLoanIsSignedLessThan(Boolean value) {
            addCriterion("loan_is_signed <", value, "loanIsSigned");
            return (Criteria) this;
        }

        public Criteria andLoanIsSignedLessThanOrEqualTo(Boolean value) {
            addCriterion("loan_is_signed <=", value, "loanIsSigned");
            return (Criteria) this;
        }

        public Criteria andLoanIsSignedIn(List<Boolean> values) {
            addCriterion("loan_is_signed in", values, "loanIsSigned");
            return (Criteria) this;
        }

        public Criteria andLoanIsSignedNotIn(List<Boolean> values) {
            addCriterion("loan_is_signed not in", values, "loanIsSigned");
            return (Criteria) this;
        }

        public Criteria andLoanIsSignedBetween(Boolean value1, Boolean value2) {
            addCriterion("loan_is_signed between", value1, value2, "loanIsSigned");
            return (Criteria) this;
        }

        public Criteria andLoanIsSignedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("loan_is_signed not between", value1, value2, "loanIsSigned");
            return (Criteria) this;
        }

        public Criteria andUserStateIsNull() {
            addCriterion("user_state is null");
            return (Criteria) this;
        }

        public Criteria andUserStateIsNotNull() {
            addCriterion("user_state is not null");
            return (Criteria) this;
        }

        public Criteria andUserStateEqualTo(Byte value) {
            addCriterion("user_state =", value, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateNotEqualTo(Byte value) {
            addCriterion("user_state <>", value, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateGreaterThan(Byte value) {
            addCriterion("user_state >", value, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateGreaterThanOrEqualTo(Byte value) {
            addCriterion("user_state >=", value, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateLessThan(Byte value) {
            addCriterion("user_state <", value, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateLessThanOrEqualTo(Byte value) {
            addCriterion("user_state <=", value, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateIn(List<Byte> values) {
            addCriterion("user_state in", values, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateNotIn(List<Byte> values) {
            addCriterion("user_state not in", values, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateBetween(Byte value1, Byte value2) {
            addCriterion("user_state between", value1, value2, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateNotBetween(Byte value1, Byte value2) {
            addCriterion("user_state not between", value1, value2, "userState");
            return (Criteria) this;
        }

        public Criteria andPwdRetryCountIsNull() {
            addCriterion("pwd_retry_count is null");
            return (Criteria) this;
        }

        public Criteria andPwdRetryCountIsNotNull() {
            addCriterion("pwd_retry_count is not null");
            return (Criteria) this;
        }

        public Criteria andPwdRetryCountEqualTo(Integer value) {
            addCriterion("pwd_retry_count =", value, "pwdRetryCount");
            return (Criteria) this;
        }

        public Criteria andPwdRetryCountNotEqualTo(Integer value) {
            addCriterion("pwd_retry_count <>", value, "pwdRetryCount");
            return (Criteria) this;
        }

        public Criteria andPwdRetryCountGreaterThan(Integer value) {
            addCriterion("pwd_retry_count >", value, "pwdRetryCount");
            return (Criteria) this;
        }

        public Criteria andPwdRetryCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("pwd_retry_count >=", value, "pwdRetryCount");
            return (Criteria) this;
        }

        public Criteria andPwdRetryCountLessThan(Integer value) {
            addCriterion("pwd_retry_count <", value, "pwdRetryCount");
            return (Criteria) this;
        }

        public Criteria andPwdRetryCountLessThanOrEqualTo(Integer value) {
            addCriterion("pwd_retry_count <=", value, "pwdRetryCount");
            return (Criteria) this;
        }

        public Criteria andPwdRetryCountIn(List<Integer> values) {
            addCriterion("pwd_retry_count in", values, "pwdRetryCount");
            return (Criteria) this;
        }

        public Criteria andPwdRetryCountNotIn(List<Integer> values) {
            addCriterion("pwd_retry_count not in", values, "pwdRetryCount");
            return (Criteria) this;
        }

        public Criteria andPwdRetryCountBetween(Integer value1, Integer value2) {
            addCriterion("pwd_retry_count between", value1, value2, "pwdRetryCount");
            return (Criteria) this;
        }

        public Criteria andPwdRetryCountNotBetween(Integer value1, Integer value2) {
            addCriterion("pwd_retry_count not between", value1, value2, "pwdRetryCount");
            return (Criteria) this;
        }

        public Criteria andDepositUserTypeIsNull() {
            addCriterion("deposit_user_type is null");
            return (Criteria) this;
        }

        public Criteria andDepositUserTypeIsNotNull() {
            addCriterion("deposit_user_type is not null");
            return (Criteria) this;
        }

        public Criteria andDepositUserTypeEqualTo(Byte value) {
            addCriterion("deposit_user_type =", value, "depositUserType");
            return (Criteria) this;
        }

        public Criteria andDepositUserTypeNotEqualTo(Byte value) {
            addCriterion("deposit_user_type <>", value, "depositUserType");
            return (Criteria) this;
        }

        public Criteria andDepositUserTypeGreaterThan(Byte value) {
            addCriterion("deposit_user_type >", value, "depositUserType");
            return (Criteria) this;
        }

        public Criteria andDepositUserTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("deposit_user_type >=", value, "depositUserType");
            return (Criteria) this;
        }

        public Criteria andDepositUserTypeLessThan(Byte value) {
            addCriterion("deposit_user_type <", value, "depositUserType");
            return (Criteria) this;
        }

        public Criteria andDepositUserTypeLessThanOrEqualTo(Byte value) {
            addCriterion("deposit_user_type <=", value, "depositUserType");
            return (Criteria) this;
        }

        public Criteria andDepositUserTypeIn(List<Byte> values) {
            addCriterion("deposit_user_type in", values, "depositUserType");
            return (Criteria) this;
        }

        public Criteria andDepositUserTypeNotIn(List<Byte> values) {
            addCriterion("deposit_user_type not in", values, "depositUserType");
            return (Criteria) this;
        }

        public Criteria andDepositUserTypeBetween(Byte value1, Byte value2) {
            addCriterion("deposit_user_type between", value1, value2, "depositUserType");
            return (Criteria) this;
        }

        public Criteria andDepositUserTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("deposit_user_type not between", value1, value2, "depositUserType");
            return (Criteria) this;
        }

        public Criteria andAutoVipSwitcherIsNull() {
            addCriterion("auto_vip_switcher is null");
            return (Criteria) this;
        }

        public Criteria andAutoVipSwitcherIsNotNull() {
            addCriterion("auto_vip_switcher is not null");
            return (Criteria) this;
        }

        public Criteria andAutoVipSwitcherEqualTo(Boolean value) {
            addCriterion("auto_vip_switcher =", value, "autoVipSwitcher");
            return (Criteria) this;
        }

        public Criteria andAutoVipSwitcherNotEqualTo(Boolean value) {
            addCriterion("auto_vip_switcher <>", value, "autoVipSwitcher");
            return (Criteria) this;
        }

        public Criteria andAutoVipSwitcherGreaterThan(Boolean value) {
            addCriterion("auto_vip_switcher >", value, "autoVipSwitcher");
            return (Criteria) this;
        }

        public Criteria andAutoVipSwitcherGreaterThanOrEqualTo(Boolean value) {
            addCriterion("auto_vip_switcher >=", value, "autoVipSwitcher");
            return (Criteria) this;
        }

        public Criteria andAutoVipSwitcherLessThan(Boolean value) {
            addCriterion("auto_vip_switcher <", value, "autoVipSwitcher");
            return (Criteria) this;
        }

        public Criteria andAutoVipSwitcherLessThanOrEqualTo(Boolean value) {
            addCriterion("auto_vip_switcher <=", value, "autoVipSwitcher");
            return (Criteria) this;
        }

        public Criteria andAutoVipSwitcherIn(List<Boolean> values) {
            addCriterion("auto_vip_switcher in", values, "autoVipSwitcher");
            return (Criteria) this;
        }

        public Criteria andAutoVipSwitcherNotIn(List<Boolean> values) {
            addCriterion("auto_vip_switcher not in", values, "autoVipSwitcher");
            return (Criteria) this;
        }

        public Criteria andAutoVipSwitcherBetween(Boolean value1, Boolean value2) {
            addCriterion("auto_vip_switcher between", value1, value2, "autoVipSwitcher");
            return (Criteria) this;
        }

        public Criteria andAutoVipSwitcherNotBetween(Boolean value1, Boolean value2) {
            addCriterion("auto_vip_switcher not between", value1, value2, "autoVipSwitcher");
            return (Criteria) this;
        }

        public Criteria andIsMigratedIsNull() {
            addCriterion("is_migrated is null");
            return (Criteria) this;
        }

        public Criteria andIsMigratedIsNotNull() {
            addCriterion("is_migrated is not null");
            return (Criteria) this;
        }

        public Criteria andIsMigratedEqualTo(Boolean value) {
            addCriterion("is_migrated =", value, "isMigrated");
            return (Criteria) this;
        }

        public Criteria andIsMigratedNotEqualTo(Boolean value) {
            addCriterion("is_migrated <>", value, "isMigrated");
            return (Criteria) this;
        }

        public Criteria andIsMigratedGreaterThan(Boolean value) {
            addCriterion("is_migrated >", value, "isMigrated");
            return (Criteria) this;
        }

        public Criteria andIsMigratedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_migrated >=", value, "isMigrated");
            return (Criteria) this;
        }

        public Criteria andIsMigratedLessThan(Boolean value) {
            addCriterion("is_migrated <", value, "isMigrated");
            return (Criteria) this;
        }

        public Criteria andIsMigratedLessThanOrEqualTo(Boolean value) {
            addCriterion("is_migrated <=", value, "isMigrated");
            return (Criteria) this;
        }

        public Criteria andIsMigratedIn(List<Boolean> values) {
            addCriterion("is_migrated in", values, "isMigrated");
            return (Criteria) this;
        }

        public Criteria andIsMigratedNotIn(List<Boolean> values) {
            addCriterion("is_migrated not in", values, "isMigrated");
            return (Criteria) this;
        }

        public Criteria andIsMigratedBetween(Boolean value1, Boolean value2) {
            addCriterion("is_migrated between", value1, value2, "isMigrated");
            return (Criteria) this;
        }

        public Criteria andIsMigratedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_migrated not between", value1, value2, "isMigrated");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_lightning
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_lightning
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}