package com.weshare.thunder.model;

public class UserLightning {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_lightning.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_lightning.user_gid
     *
     * @mbggenerated
     */
    private String userGid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_lightning.create_time
     *
     * @mbggenerated
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_lightning.update_time
     *
     * @mbggenerated
     */
    private Integer updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_lightning.invitation_code
     *
     * @mbggenerated
     */
    private String invitationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_lightning.scene_id
     *
     * @mbggenerated
     */
    private Integer sceneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_lightning.ticket
     *
     * @mbggenerated
     */
    private String ticket;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_lightning.inviter_gid
     *
     * @mbggenerated
     */
    private String inviterGid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_lightning.invited_count
     *
     * @mbggenerated
     */
    private Integer invitedCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_lightning.invited_left_count
     *
     * @mbggenerated
     */
    private Integer invitedLeftCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_lightning.is_activited
     *
     * @mbggenerated
     */
    private Boolean isActivited;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_lightning.is_certified
     *
     * @mbggenerated
     */
    private Boolean isCertified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_lightning.first_channel_from
     *
     * @mbggenerated
     */
    private String firstChannelFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_lightning.first_try_time
     *
     * @mbggenerated
     */
    private Integer firstTryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_lightning.is_auto_deposit
     *
     * @mbggenerated
     */
    private Boolean isAutoDeposit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_lightning.is_deposit
     *
     * @mbggenerated
     */
    private Boolean isDeposit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_lightning.is_loan
     *
     * @mbggenerated
     */
    private Boolean isLoan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_lightning.deposit_is_signed
     *
     * @mbggenerated
     */
    private Boolean depositIsSigned;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_lightning.loan_is_signed
     *
     * @mbggenerated
     */
    private Boolean loanIsSigned;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_lightning.user_state
     *
     * @mbggenerated
     */
    private Byte userState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_lightning.pwd_retry_count
     *
     * @mbggenerated
     */
    private Integer pwdRetryCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_lightning.deposit_user_type
     *
     * @mbggenerated
     */
    private Byte depositUserType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_lightning.auto_vip_switcher
     *
     * @mbggenerated
     */
    private Boolean autoVipSwitcher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_lightning.is_migrated
     *
     * @mbggenerated
     */
    private Boolean isMigrated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_lightning.id
     *
     * @return the value of user_lightning.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_lightning.id
     *
     * @param id the value for user_lightning.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_lightning.user_gid
     *
     * @return the value of user_lightning.user_gid
     *
     * @mbggenerated
     */
    public String getUserGid() {
        return userGid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_lightning.user_gid
     *
     * @param userGid the value for user_lightning.user_gid
     *
     * @mbggenerated
     */
    public void setUserGid(String userGid) {
        this.userGid = userGid == null ? null : userGid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_lightning.create_time
     *
     * @return the value of user_lightning.create_time
     *
     * @mbggenerated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_lightning.create_time
     *
     * @param createTime the value for user_lightning.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_lightning.update_time
     *
     * @return the value of user_lightning.update_time
     *
     * @mbggenerated
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_lightning.update_time
     *
     * @param updateTime the value for user_lightning.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_lightning.invitation_code
     *
     * @return the value of user_lightning.invitation_code
     *
     * @mbggenerated
     */
    public String getInvitationCode() {
        return invitationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_lightning.invitation_code
     *
     * @param invitationCode the value for user_lightning.invitation_code
     *
     * @mbggenerated
     */
    public void setInvitationCode(String invitationCode) {
        this.invitationCode = invitationCode == null ? null : invitationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_lightning.scene_id
     *
     * @return the value of user_lightning.scene_id
     *
     * @mbggenerated
     */
    public Integer getSceneId() {
        return sceneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_lightning.scene_id
     *
     * @param sceneId the value for user_lightning.scene_id
     *
     * @mbggenerated
     */
    public void setSceneId(Integer sceneId) {
        this.sceneId = sceneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_lightning.ticket
     *
     * @return the value of user_lightning.ticket
     *
     * @mbggenerated
     */
    public String getTicket() {
        return ticket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_lightning.ticket
     *
     * @param ticket the value for user_lightning.ticket
     *
     * @mbggenerated
     */
    public void setTicket(String ticket) {
        this.ticket = ticket == null ? null : ticket.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_lightning.inviter_gid
     *
     * @return the value of user_lightning.inviter_gid
     *
     * @mbggenerated
     */
    public String getInviterGid() {
        return inviterGid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_lightning.inviter_gid
     *
     * @param inviterGid the value for user_lightning.inviter_gid
     *
     * @mbggenerated
     */
    public void setInviterGid(String inviterGid) {
        this.inviterGid = inviterGid == null ? null : inviterGid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_lightning.invited_count
     *
     * @return the value of user_lightning.invited_count
     *
     * @mbggenerated
     */
    public Integer getInvitedCount() {
        return invitedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_lightning.invited_count
     *
     * @param invitedCount the value for user_lightning.invited_count
     *
     * @mbggenerated
     */
    public void setInvitedCount(Integer invitedCount) {
        this.invitedCount = invitedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_lightning.invited_left_count
     *
     * @return the value of user_lightning.invited_left_count
     *
     * @mbggenerated
     */
    public Integer getInvitedLeftCount() {
        return invitedLeftCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_lightning.invited_left_count
     *
     * @param invitedLeftCount the value for user_lightning.invited_left_count
     *
     * @mbggenerated
     */
    public void setInvitedLeftCount(Integer invitedLeftCount) {
        this.invitedLeftCount = invitedLeftCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_lightning.is_activited
     *
     * @return the value of user_lightning.is_activited
     *
     * @mbggenerated
     */
    public Boolean getIsActivited() {
        return isActivited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_lightning.is_activited
     *
     * @param isActivited the value for user_lightning.is_activited
     *
     * @mbggenerated
     */
    public void setIsActivited(Boolean isActivited) {
        this.isActivited = isActivited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_lightning.is_certified
     *
     * @return the value of user_lightning.is_certified
     *
     * @mbggenerated
     */
    public Boolean getIsCertified() {
        return isCertified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_lightning.is_certified
     *
     * @param isCertified the value for user_lightning.is_certified
     *
     * @mbggenerated
     */
    public void setIsCertified(Boolean isCertified) {
        this.isCertified = isCertified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_lightning.first_channel_from
     *
     * @return the value of user_lightning.first_channel_from
     *
     * @mbggenerated
     */
    public String getFirstChannelFrom() {
        return firstChannelFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_lightning.first_channel_from
     *
     * @param firstChannelFrom the value for user_lightning.first_channel_from
     *
     * @mbggenerated
     */
    public void setFirstChannelFrom(String firstChannelFrom) {
        this.firstChannelFrom = firstChannelFrom == null ? null : firstChannelFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_lightning.first_try_time
     *
     * @return the value of user_lightning.first_try_time
     *
     * @mbggenerated
     */
    public Integer getFirstTryTime() {
        return firstTryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_lightning.first_try_time
     *
     * @param firstTryTime the value for user_lightning.first_try_time
     *
     * @mbggenerated
     */
    public void setFirstTryTime(Integer firstTryTime) {
        this.firstTryTime = firstTryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_lightning.is_auto_deposit
     *
     * @return the value of user_lightning.is_auto_deposit
     *
     * @mbggenerated
     */
    public Boolean getIsAutoDeposit() {
        return isAutoDeposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_lightning.is_auto_deposit
     *
     * @param isAutoDeposit the value for user_lightning.is_auto_deposit
     *
     * @mbggenerated
     */
    public void setIsAutoDeposit(Boolean isAutoDeposit) {
        this.isAutoDeposit = isAutoDeposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_lightning.is_deposit
     *
     * @return the value of user_lightning.is_deposit
     *
     * @mbggenerated
     */
    public Boolean getIsDeposit() {
        return isDeposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_lightning.is_deposit
     *
     * @param isDeposit the value for user_lightning.is_deposit
     *
     * @mbggenerated
     */
    public void setIsDeposit(Boolean isDeposit) {
        this.isDeposit = isDeposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_lightning.is_loan
     *
     * @return the value of user_lightning.is_loan
     *
     * @mbggenerated
     */
    public Boolean getIsLoan() {
        return isLoan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_lightning.is_loan
     *
     * @param isLoan the value for user_lightning.is_loan
     *
     * @mbggenerated
     */
    public void setIsLoan(Boolean isLoan) {
        this.isLoan = isLoan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_lightning.deposit_is_signed
     *
     * @return the value of user_lightning.deposit_is_signed
     *
     * @mbggenerated
     */
    public Boolean getDepositIsSigned() {
        return depositIsSigned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_lightning.deposit_is_signed
     *
     * @param depositIsSigned the value for user_lightning.deposit_is_signed
     *
     * @mbggenerated
     */
    public void setDepositIsSigned(Boolean depositIsSigned) {
        this.depositIsSigned = depositIsSigned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_lightning.loan_is_signed
     *
     * @return the value of user_lightning.loan_is_signed
     *
     * @mbggenerated
     */
    public Boolean getLoanIsSigned() {
        return loanIsSigned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_lightning.loan_is_signed
     *
     * @param loanIsSigned the value for user_lightning.loan_is_signed
     *
     * @mbggenerated
     */
    public void setLoanIsSigned(Boolean loanIsSigned) {
        this.loanIsSigned = loanIsSigned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_lightning.user_state
     *
     * @return the value of user_lightning.user_state
     *
     * @mbggenerated
     */
    public Byte getUserState() {
        return userState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_lightning.user_state
     *
     * @param userState the value for user_lightning.user_state
     *
     * @mbggenerated
     */
    public void setUserState(Byte userState) {
        this.userState = userState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_lightning.pwd_retry_count
     *
     * @return the value of user_lightning.pwd_retry_count
     *
     * @mbggenerated
     */
    public Integer getPwdRetryCount() {
        return pwdRetryCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_lightning.pwd_retry_count
     *
     * @param pwdRetryCount the value for user_lightning.pwd_retry_count
     *
     * @mbggenerated
     */
    public void setPwdRetryCount(Integer pwdRetryCount) {
        this.pwdRetryCount = pwdRetryCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_lightning.deposit_user_type
     *
     * @return the value of user_lightning.deposit_user_type
     *
     * @mbggenerated
     */
    public Byte getDepositUserType() {
        return depositUserType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_lightning.deposit_user_type
     *
     * @param depositUserType the value for user_lightning.deposit_user_type
     *
     * @mbggenerated
     */
    public void setDepositUserType(Byte depositUserType) {
        this.depositUserType = depositUserType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_lightning.auto_vip_switcher
     *
     * @return the value of user_lightning.auto_vip_switcher
     *
     * @mbggenerated
     */
    public Boolean getAutoVipSwitcher() {
        return autoVipSwitcher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_lightning.auto_vip_switcher
     *
     * @param autoVipSwitcher the value for user_lightning.auto_vip_switcher
     *
     * @mbggenerated
     */
    public void setAutoVipSwitcher(Boolean autoVipSwitcher) {
        this.autoVipSwitcher = autoVipSwitcher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_lightning.is_migrated
     *
     * @return the value of user_lightning.is_migrated
     *
     * @mbggenerated
     */
    public Boolean getIsMigrated() {
        return isMigrated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_lightning.is_migrated
     *
     * @param isMigrated the value for user_lightning.is_migrated
     *
     * @mbggenerated
     */
    public void setIsMigrated(Boolean isMigrated) {
        this.isMigrated = isMigrated;
    }


    public void clear(){
        id = null;
        userGid = null;
        createTime = null;
        updateTime = null;
        invitationCode = null;
        sceneId=null;
        ticket = null;
        inviterGid =null;
        invitedCount = null;
        invitedLeftCount = null;
        isActivited = null;
        isCertified = null;
        firstChannelFrom = null;
        firstTryTime = null;
        isAutoDeposit = null;
        isDeposit = null;
        isLoan = null;
        depositIsSigned = null;
        loanIsSigned = null;
        userState = null;
        pwdRetryCount = null;
        depositUserType = null;
        autoVipSwitcher = null;
        isMigrated = null;
    }

    //Customer Definations
    public static final byte STATE_NORMAL = 0;
    public static final byte STATE_FROZON = 1;
    public static final byte STATE_DELETED = 2;
    public static final byte STATE_LOGOUT = 3;
    public static final byte STATE_PWDLOCK = 4;

    public static final byte USER_TYPE_NORMAL = 0;
    public static final byte USER_TYPE_BUSSINESS = 1;
    public static final byte USER_TYPE_BIGCUSTOMER = 2;
    public static final byte USER_TYPE_STAKEHOLDER = 3;
    public static final byte USER_TYPE_DEALER = 4;


}