package com.weshare.thunder.model;

public class UserChannelWechat {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_channel_wechat.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_channel_wechat.user_gid
     *
     * @mbggenerated
     */
    private String userGid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_channel_wechat.union_id
     *
     * @mbggenerated
     */
    private String unionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_channel_wechat.open_id
     *
     * @mbggenerated
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_channel_wechat.create_time
     *
     * @mbggenerated
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_channel_wechat.update_time
     *
     * @mbggenerated
     */
    private Integer updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_channel_wechat.company_openid
     *
     * @mbggenerated
     */
    private String companyOpenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_channel_wechat.is_followed
     *
     * @mbggenerated
     */
    private Boolean isFollowed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_channel_wechat.follow_way
     *
     * @mbggenerated
     */
    private Integer followWay;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_channel_wechat.id
     *
     * @return the value of user_channel_wechat.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_channel_wechat.id
     *
     * @param id the value for user_channel_wechat.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_channel_wechat.user_gid
     *
     * @return the value of user_channel_wechat.user_gid
     *
     * @mbggenerated
     */
    public String getUserGid() {
        return userGid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_channel_wechat.user_gid
     *
     * @param userGid the value for user_channel_wechat.user_gid
     *
     * @mbggenerated
     */
    public void setUserGid(String userGid) {
        this.userGid = userGid == null ? null : userGid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_channel_wechat.union_id
     *
     * @return the value of user_channel_wechat.union_id
     *
     * @mbggenerated
     */
    public String getUnionId() {
        return unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_channel_wechat.union_id
     *
     * @param unionId the value for user_channel_wechat.union_id
     *
     * @mbggenerated
     */
    public void setUnionId(String unionId) {
        this.unionId = unionId == null ? null : unionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_channel_wechat.open_id
     *
     * @return the value of user_channel_wechat.open_id
     *
     * @mbggenerated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_channel_wechat.open_id
     *
     * @param openId the value for user_channel_wechat.open_id
     *
     * @mbggenerated
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_channel_wechat.create_time
     *
     * @return the value of user_channel_wechat.create_time
     *
     * @mbggenerated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_channel_wechat.create_time
     *
     * @param createTime the value for user_channel_wechat.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_channel_wechat.update_time
     *
     * @return the value of user_channel_wechat.update_time
     *
     * @mbggenerated
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_channel_wechat.update_time
     *
     * @param updateTime the value for user_channel_wechat.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_channel_wechat.company_openid
     *
     * @return the value of user_channel_wechat.company_openid
     *
     * @mbggenerated
     */
    public String getCompanyOpenid() {
        return companyOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_channel_wechat.company_openid
     *
     * @param companyOpenid the value for user_channel_wechat.company_openid
     *
     * @mbggenerated
     */
    public void setCompanyOpenid(String companyOpenid) {
        this.companyOpenid = companyOpenid == null ? null : companyOpenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_channel_wechat.is_followed
     *
     * @return the value of user_channel_wechat.is_followed
     *
     * @mbggenerated
     */
    public Boolean getIsFollowed() {
        return isFollowed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_channel_wechat.is_followed
     *
     * @param isFollowed the value for user_channel_wechat.is_followed
     *
     * @mbggenerated
     */
    public void setIsFollowed(Boolean isFollowed) {
        this.isFollowed = isFollowed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_channel_wechat.follow_way
     *
     * @return the value of user_channel_wechat.follow_way
     *
     * @mbggenerated
     */
    public Integer getFollowWay() {
        return followWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_channel_wechat.follow_way
     *
     * @param followWay the value for user_channel_wechat.follow_way
     *
     * @mbggenerated
     */
    public void setFollowWay(Integer followWay) {
        this.followWay = followWay;
    }

    public final static int FOLLOW_WAY_NORMAL = 0;
    public final static int FOLLOW_WAY_SCAN = 1;
    public final static int FOLLOW_WAY_AUTHORIZE = 2;
    public final static int FOLLOW_WAY_AUTHORIZE_FOLLOW = 3;
    public final static int FOLLOW_WAY_INVITATION = 4;
    public final static int FOLLOW_WAY_MANUAL_MIGRATE = 5;
    public final static int FOLLOW_WAY_SECOND_WECHAT = 6;

    public void clear() {
        id = null;
        userGid = null;
        unionId = null;
        openId = null;
        createTime = null;
        updateTime = null;
        companyOpenid = null;
        isFollowed = null;
        followWay = null;
    }
}